using System.Globalization;
using System.Text;
using Polhem.Core;
using Polhem.Db.Ddl;
using Polhem.Definition.Database;

namespace Polhem.Db.Providers.PostgreSql
{
    /// <summary>
    /// Generates CREATE TABLE SQL statements for PostgreSQL. Counterpart to
    /// <see cref="SqlServer.SqlCreateTableCommandBuilder"/> with PG-specific dialect:
    /// double-quoted identifiers, <c>GENERATED BY DEFAULT AS IDENTITY</c> for auto-increment,
    /// and <c>COMMENT ON TABLE/COLUMN</c> for descriptions.
    /// </summary>
    public sealed class PgCreateTableCommandBuilder : ICreateTableCommandBuilder
    {
        private TableSchema? _dbTable;

        /// <summary>
        /// Initializes a new instance of <see cref="PgCreateTableCommandBuilder"/>.
        /// </summary>
        public PgCreateTableCommandBuilder()
        { }

        /// <summary>
        /// Gets the table schema definition.
        /// </summary>
        private TableSchema TableSchema => _dbTable!;

        /// <summary>
        /// Gets the SQL statement for creating a table.
        /// </summary>
        /// <param name="tableSchema">The table schema definition.</param>
        public string GetCommandText(TableSchema tableSchema)
        {
            _dbTable = tableSchema;
            return $"-- Create table {this.TableSchema.TableName}\r\n{this.GetCreateTableCommandText()}";
        }

        /// <summary>
        /// Gets the CREATE TABLE SQL statement (with PK constraint and trailing CREATE INDEX / COMMENT statements).
        /// </summary>
        private string GetCreateTableCommandText()
        {
            string tableName = this.TableSchema.TableName;
            string fields = GetFieldsCommandText();
            string primaryKey = GetPrimaryKeyCommandText(tableName);
            string indexes = GetIndexesCommandText(tableName);
            string comments = GetCommentCommandText(tableName);

            var sb = new StringBuilder();
            sb.Append(CultureInfo.InvariantCulture, $"CREATE TABLE {PgSchemaSyntax.QuoteName(tableName)} (\r\n{fields}");
            if (StringUtilities.IsNotEmpty(primaryKey))
                sb.Append(CultureInfo.InvariantCulture, $",\r\n  {primaryKey}");
            sb.Append("\r\n);");
            if (StringUtilities.IsNotEmpty(indexes))
                sb.Append(CultureInfo.InvariantCulture, $"\r\n{indexes}");
            if (StringUtilities.IsNotEmpty(comments))
                sb.Append(CultureInfo.InvariantCulture, $"\r\n{comments}");
            return sb.ToString();
        }

        /// <summary>
        /// Gets the SQL fragment for all column definitions.
        /// </summary>
        private string GetFieldsCommandText()
        {
            var sb = new StringBuilder();
            foreach (DbField field in this.TableSchema.Fields!)
            {
                if (sb.Length > 0)
                    sb.Append(",\r\n");
                sb.Append("  " + PgSchemaSyntax.GetColumnDefinition(field));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Gets the inline PRIMARY KEY constraint SQL fragment.
        /// </summary>
        /// <remarks>
        /// PostgreSQL rejects ASC/DESC inside a PRIMARY KEY (or UNIQUE) constraint
        /// (<c>syntax error at or near "ASC"</c>); per-column sort direction is only valid
        /// on regular indexes. Emit bare column names here.
        /// </remarks>
        /// <param name="tableName">The table name.</param>
        private string GetPrimaryKeyCommandText(string tableName)
        {
            var index = this.TableSchema.GetPrimaryKey();
            if (index == null) return string.Empty;

            var fieldBuilder = new StringBuilder();
            foreach (IndexField field in index.IndexFields!)
            {
                if (fieldBuilder.Length > 0)
                    fieldBuilder.Append(", ");
                fieldBuilder.Append(PgSchemaSyntax.QuoteName(field.FieldName));
            }

            string name = StringUtilities.Format(index.Name, tableName);
            return $"CONSTRAINT {PgSchemaSyntax.QuoteName(name)} PRIMARY KEY ({fieldBuilder})";
        }

        /// <summary>
        /// Gets the SQL statements for creating all non-primary-key indexes.
        /// </summary>
        /// <param name="tableName">The table name.</param>
        private string GetIndexesCommandText(string tableName)
            => IndexStatementJoiner.Join(this.TableSchema.Indexes, tableName, GetIndexCommandText);

        /// <summary>
        /// Gets the SQL statement for creating a single index.
        /// </summary>
        /// <param name="tableName">The table name.</param>
        /// <param name="index">The table schema index definition.</param>
        private static string GetIndexCommandText(string tableName, DbTableIndex index)
        {
            string name = StringUtilities.Format(index.Name, tableName);
            var fieldBuilder = new StringBuilder();
            foreach (IndexField field in index.IndexFields!)
            {
                if (fieldBuilder.Length > 0)
                    fieldBuilder.Append(", ");
                fieldBuilder.Append(CultureInfo.InvariantCulture,
                    $"{PgSchemaSyntax.QuoteName(field.FieldName)} {field.SortDirection.ToString().ToUpperInvariant()}");
            }

            string uniqueClause = index.Unique ? "UNIQUE " : string.Empty;
            return $"CREATE {uniqueClause}INDEX {PgSchemaSyntax.QuoteName(name)} ON {PgSchemaSyntax.QuoteName(tableName)} ({fieldBuilder});";
        }

        /// <summary>
        /// Gets the COMMENT ON TABLE / COLUMN statements that replicate the table's
        /// <see cref="TableSchema.DisplayName"/> and each column's <see cref="DbField.Caption"/>.
        /// </summary>
        /// <param name="tableName">The table name.</param>
        private string GetCommentCommandText(string tableName)
        {
            var sb = new StringBuilder();
            if (StringUtilities.IsNotEmpty(this.TableSchema.DisplayName))
                sb.AppendLine(PgSchemaSyntax.GetTableCommentStatement(tableName, this.TableSchema.DisplayName));

            foreach (var field in this.TableSchema.Fields!.Where(f => StringUtilities.IsNotEmpty(f.Caption)))
            {
                sb.AppendLine(PgSchemaSyntax.GetColumnCommentStatement(tableName, field.FieldName, field.Caption));
            }
            return sb.ToString().Trim();
        }
    }
}
