using Polhem.Base.Data;
using Polhem.Definition.Database;

namespace Polhem.Db.Providers.PostgreSql
{
    /// <summary>
    /// Converts between <see cref="FieldDbType"/> and PostgreSQL column type expressions.
    /// </summary>
    internal static class PgTypeMapping
    {
        /// <summary>
        /// Returns the PostgreSQL column type expression for the given field definition
        /// (e.g. <c>varchar(50)</c>, <c>numeric(18,2)</c>, <c>uuid</c>).
        /// </summary>
        /// <param name="field">The field definition.</param>
        public static string GetPgType(DbField field)
        {
            switch (field.DbType)
            {
                case FieldDbType.String:
                    return $"varchar({field.Length})";
                case FieldDbType.Text:
                    return "text";
                case FieldDbType.Time:
                    return "char(5)";
                case FieldDbType.Boolean:
                    return "boolean";
                case FieldDbType.AutoIncrement:
                    return "integer GENERATED BY DEFAULT AS IDENTITY";
                case FieldDbType.Short:
                    return "smallint";
                case FieldDbType.Integer:
                    return "integer";
                case FieldDbType.Long:
                    return "bigint";
                case FieldDbType.Decimal:
                    {
                        int precision = field.Precision > 0 ? field.Precision : 18;
                        int scale = field.Scale > 0 ? field.Scale : 0;
                        return $"numeric({precision},{scale})";
                    }
                case FieldDbType.Currency:
                    return "numeric(19,4)";
                case FieldDbType.Date:
                    return "date";
                case FieldDbType.DateTime:
                    return "timestamp";
                case FieldDbType.Guid:
                    return "uuid";
                case FieldDbType.Binary:
                    return "bytea";
                default:
                    throw new InvalidOperationException($"DbType={field.DbType} is not supported");
            }
        }
    }
}
