using Polhem.Api.Contracts.System;

namespace Polhem.Api.Core.Messages.System
{
    /// <summary>
    /// API request for the login operation.
    /// </summary>
    public class LoginRequest : ApiRequest, ILoginRequest
    {
        /// <summary>
        /// Gets or sets the user account identifier.
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the password (plain text or pre-encrypted).
        /// </summary>
        public string Password { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the RSA public key generated by the client for key exchange.
        /// </summary>
        public string ClientPublicKey { get; set; } = string.Empty;
    }
}
