<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>QuickStart.Server</RootNamespace>
    <AssemblyName>QuickStart.Server</AssemblyName>
    <IsPackable>false</IsPackable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Polhem.Api.AspNetCore\Polhem.Api.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\Polhem.Db\Polhem.Db.csproj" />
    <ProjectReference Include="..\Polhem.Samples.Shared\Polhem.Samples.Shared.csproj" />
  </ItemGroup>

</Project>
