namespace Polhem.Api.Contracts.System
{
    /// <summary>
    /// Contract interface for login request parameters.
    /// </summary>
    public interface ILoginRequest
    {
        /// <summary>
        /// Gets the user account identifier.
        /// </summary>
        string UserId { get; }

        /// <summary>
        /// Gets the password (plain text or pre-encrypted).
        /// </summary>
        string Password { get; }

        /// <summary>
        /// Gets the RSA public key generated by the client for key exchange.
        /// </summary>
        string ClientPublicKey { get; }
    }
}
