using System.ComponentModel;

namespace Polhem.Base.UnitTests
{
    /// <summary>
    /// <c>Polhem.Base</c> must not gain the ability to make outbound network requests.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This assembly is a dependency of **every** project, including UI heads that only read definition files,
    /// the offline definition editor and generators. Any capability placed here appears on the public surface of
    /// every consumer, whether it needs it or not. <c>HttpUtilities</c> once lived here, and its callers were only
    /// ever in <c>Polhem.Api.Client</c>.
    /// </para>
    /// <para>
    /// The gate blocks <c>System.Net.Http</c> (the stack that opens outbound connections), not all of
    /// <c>System.Net</c>: parsing and comparing values such as <c>IPAddress</c> connects nowhere. A gate that
    /// conflated the two would push people to move the wrong things just to pass it.
    /// </para>
    /// <para>
    /// It checks IL references rather than <c>deps.json</c>: the <c>global using System.Net.Http;</c> generated by
    /// <c>ImplicitUsings</c> does not create an assembly reference by itself; only actually using a type does.
    /// </para>
    /// </remarks>
    public class BaseLayerCapabilityGateTests
    {
        [Fact]
        [DisplayName("Polhem.Base does not reference System.Net.Http (network primitives belong to higher layers)")]
        public void BaseAssembly_DoesNotReferenceHttpStack()
        {
            var referenced = typeof(SysInfo).Assembly
                .GetReferencedAssemblies()
                .Select(name => name.Name)
                .ToArray();

            // Control check: the reference list was really read, so an empty array cannot make the assertion pass vacuously.
            Assert.Contains("System.Runtime", referenced, StringComparer.OrdinalIgnoreCase);

            Assert.DoesNotContain("System.Net.Http", referenced, StringComparer.OrdinalIgnoreCase);
        }
    }
}
