using System.Collections.ObjectModel;
using System.Globalization;
using Avalonia.Controls.ApplicationLifetimes;
using Polhem.DefineEditor.Models;
using Polhem.DefineEditor.Services;
using Polhem.DefineEditor.Views;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace Polhem.DefineEditor.ViewModels;

/// <summary>
/// Base type for the right-pane document editors. Every concrete editor (FormSchema,
/// singleton settings, etc.) inherits this so the shell can host them through the
/// <see cref="Avalonia.Controls.TabControl"/> in MainWindow with views resolved via
/// <see cref="ViewLocator"/>.
/// </summary>
public abstract partial class DocumentViewModelBase : ViewModelBase, IDisposable
{
    /// <summary>
    /// Unsubscribe callbacks queued by <see cref="RegisterCultureHandler"/>.
    /// Flushed by <see cref="Dispose"/> so handlers held by the
    /// <see cref="LocalizationService"/> singleton don't pin the closed
    /// document forever.
    /// </summary>
    private readonly List<Action> _disposeActions = new();

    protected DocumentViewModelBase()
    {
        // StatusText is a stored snapshot (not a live binding), so a language
        // switch doesn't rewrite it automatically. Re-apply the default hint
        // when the culture changes — but only if the user hasn't replaced it
        // with an action message (Save / Validate / Add ...), so we don't
        // wipe their feedback.
        RegisterCultureHandler((_, _) =>
        {
            var newHint = L("Status_SingletonHint");
            if (StatusText == _lastDefaultHint)
                StatusText = newHint;
            _lastDefaultHint = newHint;
        });
    }

    /// <summary>Header shown in the tab and inside the document.</summary>
    public abstract string Title { get; }

    /// <summary>
    /// Stable identity used by the shell to detect "already open" — typically the
    /// canonical file path. Two documents with the same key are treated as the
    /// same tab; selecting the source node activates it rather than re-loading.
    /// </summary>
    public abstract string DocumentKey { get; }

    /// <summary>
    /// Tracks unsaved edits so the tab can show a modified indicator. Concrete
    /// editors set this when their underlying schema is mutated and clear it on
    /// successful save.
    /// </summary>
    [ObservableProperty]
    private bool _isDirty;

    /// <summary>
    /// Bottom-status hint shown for this document tab. Concrete editors
    /// overwrite it with action feedback ("Saved", "Validation passed", ...);
    /// the base ctor seeds it with the singleton-edit hint and refreshes it
    /// across culture switches via <see cref="RegisterCultureHandler"/> below.
    /// </summary>
    [ObservableProperty]
    private string _statusText = L("Status_SingletonHint");

    /// <summary>
    /// Most recent default hint value written to <see cref="StatusText"/>.
    /// Used by the culture-change handler to detect whether the user has
    /// replaced the hint with an action message; if so, we leave their
    /// feedback alone instead of stamping the new-locale hint on top.
    /// </summary>
    private string _lastDefaultHint = L("Status_SingletonHint");

    /// <summary>
    /// Resource key of the geometry shown left of the title in the tab. Looked
    /// up against the application-level resource dictionary via the icon-key
    /// converter (see <see cref="Converters.IconKeyToGeometryConverter"/>).
    /// </summary>
    public virtual string TabIcon => "DefUnknown";

    /// <summary>
    /// File-level save command surfaced uniformly through the base type so the
    /// application menu can forward "Save" to the active document without
    /// reflecting on each concrete view-model. Returns <c>null</c> for documents
    /// that don't support saving (e.g. unsupported / fallback views) — the menu
    /// item disables itself in that case.
    /// </summary>
    /// <remarks>
    /// Concrete view-models override this to return their own
    /// <c>SaveCommand</c> generated by <c>[RelayCommand]</c>. Kept separate
    /// from the generated property name to avoid clashing with the source
    /// generator (which doesn't emit <c>override</c>).
    /// </remarks>
    public virtual IRelayCommand? FileSaveCommand => null;

    /// <summary>
    /// File-level validation command surfaced uniformly through the base type;
    /// see <see cref="FileSaveCommand"/> for the rationale.
    /// </summary>
    public virtual IRelayCommand? FileValidateCommand => null;

    /// <summary>
    /// Raised when a document editor writes a define file other than its own — currently only
    /// FormSchema generating its FormLayout. Carries the absolute path of the written file.
    /// </summary>
    /// <remarks>
    /// A document view-model has no reference to the solution tree, so it cannot refresh the tree
    /// or open the new file itself. The main window owns both and subscribes to this instead,
    /// which keeps the dependency pointing one way.
    /// </remarks>
    public event EventHandler<string>? DefineFileGenerated;

    /// <summary>Raises <see cref="DefineFileGenerated"/> for <paramref name="filePath"/>.</summary>
    protected void OnDefineFileGenerated(string filePath)
        => DefineFileGenerated?.Invoke(this, filePath);

    /// <summary>
    /// Replays <paramref name="issues"/> into <paramref name="issuesPanel"/> and,
    /// when any error-severity finding is present, prompts the user via a modal
    /// dialog whether to save anyway. Returns <c>true</c> when the caller should
    /// proceed with the file write; <c>false</c> when the user cancelled.
    /// </summary>
    /// <remarks>
    /// In headless contexts (smoke tests; no <see cref="IClassicDesktopStyleApplicationLifetime"/>)
    /// the dialog is skipped and the call resolves to <c>true</c> so saves still
    /// proceed without UI interaction.
    /// </remarks>
    protected static async Task<bool> ConfirmSaveAfterValidationAsync(
        IReadOnlyList<ValidationIssue> issues,
        ObservableCollection<ValidationIssue> issuesPanel)
    {
        issuesPanel.Clear();
        foreach (var issue in issues)
            issuesPanel.Add(issue);

        var errors = issues.Count(i => i.Severity == ValidationSeverity.Error);
        if (errors == 0) return true;

        var owner = GetOwnerWindow();
        if (owner is null) return true; // smoke / headless

        var warns = issues.Count(i => i.Severity == ValidationSeverity.Warning);
        var message = warns > 0
            ? L("Confirm_SaveAfterValidationErrorsAndWarnings", errors, warns)
            : L("Confirm_SaveAfterValidationErrors", errors);
        return await ConfirmationDialog.ShowAsync(
            owner,
            L("Confirm_SaveAfterValidationTitle"),
            message,
            confirmLabel: L("Action_SaveAnyway"),
            cancelLabel: L("Action_Cancel"));
    }

    // GetOwnerWindow / L() helpers live on ViewModelBase so MainWindowViewModel
    // (and any other VM that doesn't derive from DocumentViewModelBase) can use
    // them too.

    /// <summary>
    /// Prompts the user to confirm deletion of a tree node and returns the
    /// answer. <paramref name="label"/> is the node's display text and goes
    /// into the message body. In headless / smoke contexts the dialog is
    /// skipped and the call resolves to <c>true</c>.
    /// </summary>
    protected static async Task<bool> ConfirmDeleteAsync(string label)
    {
        var owner = GetOwnerWindow();
        if (owner is null) return true;
        var displayLabel = string.IsNullOrEmpty(label) ? "—" : label;
        return await ConfirmationDialog.ShowAsync(
            owner,
            L("Confirm_DeleteTitle"),
            L("Confirm_DeleteMessage", displayLabel),
            confirmLabel: L("Action_Delete"),
            cancelLabel: L("Action_Cancel"));
    }

    /// <summary>
    /// Subscribes <paramref name="handler"/> to <see cref="LocalizationService.CultureChanged"/>
    /// and queues a matching unsubscribe to run on <see cref="Dispose"/>.
    /// Use this in place of touching the event directly — the service is a
    /// process-wide singleton, so a leaked handler keeps the entire document
    /// view-model rooted past tab close.
    /// </summary>
    protected void RegisterCultureHandler(EventHandler<CultureInfo> handler)
    {
        LocalizationService.Current.CultureChanged += handler;
        _disposeActions.Add(() => LocalizationService.Current.CultureChanged -= handler);
    }

    public virtual void Dispose()
    {
        foreach (var action in _disposeActions) action();
        _disposeActions.Clear();
        GC.SuppressFinalize(this);
    }
}
