namespace Polhem.Definition.Database
{
    /// <summary>
    /// Field type.
    /// </summary>
    public enum FieldType
    {
        /// <summary>
        /// A field that physically exists in the database table.
        /// </summary>
        DbField,
        /// <summary>
        /// A relation field retrieved from another table via a JOIN operation.
        /// </summary>
        RelationField,
        /// <summary>
        /// A virtual field generated by a calculation or expression.
        /// </summary>
        VirtualField
    }
}
