using System.Globalization;
using System.Text;
using Polhem.Base;
using Polhem.Base.Data;
using Polhem.Db.Ddl;
using Polhem.Definition.Database;

namespace Polhem.Db.Providers.Oracle
{
    /// <summary>
    /// Generates CREATE TABLE SQL statements for Oracle 19c+. Counterpart to
    /// <see cref="MySql.MySqlCreateTableCommandBuilder"/> and
    /// <see cref="Sqlite.SqliteCreateTableCommandBuilder"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Dialect-specific output:
    /// </para>
    /// <list type="bullet">
    /// <item>Double-quoted identifiers; FormSchema convention is lowercase to side-step the
    ///       case-sensitivity that quoted identifiers introduce on Oracle.</item>
    /// <item><c>NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL</c> for AutoIncrement
    ///       columns. Oracle does not support an inline column-level PRIMARY KEY clause,
    ///       so the PK is always emitted as a table-level <c>CONSTRAINT ... PRIMARY KEY</c>
    ///       (unlike MySQL/SQLite which inline it on the AutoIncrement column line).</item>
    ///  <item>Captions are not emitted inline: Oracle stores table/column captions in
    ///       <c>ALL_TAB_COMMENTS</c> / <c>ALL_COL_COMMENTS</c>, populated by trailing
    ///       <c>COMMENT ON TABLE</c> / <c>COMMENT ON COLUMN</c> statements after the table
    ///       is created.</item>
    /// <item>Case-insensitive comparison is set per-session by the connection initializer
    ///       (<c>ALTER SESSION SET NLS_COMP='LINGUISTIC' NLS_SORT='BINARY_CI'</c>), not via
    ///       column-level COLLATE — so the CREATE TABLE output stays free of per-column
    ///       collation clauses.</item>
    /// </list>
    /// <para>
    /// Oracle.ManagedDataAccess accepts only one SQL statement per command (ORA-03405),
    /// so the multiple statements (CREATE TABLE + COMMENT ON + CREATE INDEX) are wrapped
    /// in a PL/SQL anonymous block and dispatched via <c>EXECUTE IMMEDIATE</c>. Other
    /// dialects rely on the driver's built-in semicolon splitting, but on Oracle the block
    /// form is the only safe way to ship a multi-statement script through ADO.NET.
    /// </para>
    /// </remarks>
    public sealed class OracleCreateTableCommandBuilder : ICreateTableCommandBuilder
    {
        private TableSchema? _dbTable;

        /// <summary>
        /// Initializes a new instance of <see cref="OracleCreateTableCommandBuilder"/>.
        /// </summary>
        public OracleCreateTableCommandBuilder()
        { }

        /// <summary>
        /// Gets the table schema definition.
        /// </summary>
        private TableSchema TableSchema => _dbTable!;

        /// <summary>
        /// Gets the SQL statement(s) for creating a table, wrapped in a PL/SQL anonymous
        /// block so multiple DDL statements (CREATE TABLE + COMMENT ON + CREATE INDEX)
        /// can be dispatched through Oracle.ManagedDataAccess in a single call.
        /// </summary>
        /// <param name="tableSchema">The table schema definition.</param>
        public string GetCommandText(TableSchema tableSchema)
        {
            _dbTable = tableSchema;
            ValidateAutoIncrement();
            var statements = BuildRawStatements();
            return BuildPlSqlBlock(this.TableSchema.TableName, statements);
        }

        /// <summary>
        /// Wraps the supplied DDL statements in a PL/SQL anonymous block, escaping single
        /// quotes inside each statement so Oracle parses them as a literal. Each statement
        /// is dispatched via <c>EXECUTE IMMEDIATE</c>; trailing semicolons are not included
        /// inside the EXECUTE IMMEDIATE literal (DDL there must not be terminated).
        /// </summary>
        internal static string BuildPlSqlBlock(string tableName, IReadOnlyList<string> statements)
        {
            var sb = new StringBuilder();
            sb.Append(CultureInfo.InvariantCulture, $"-- Create table {tableName}\r\n");
            sb.Append("BEGIN\r\n");
            foreach (var stmt in statements)
            {
                sb.Append("  EXECUTE IMMEDIATE '");
                sb.Append(stmt.Replace("'", "''"));
                sb.Append("';\r\n");
            }
            sb.Append("END;");
            return sb.ToString();
        }

        /// <summary>
        /// Builds the ordered list of single-statement DDL strings (no trailing semicolons,
        /// no PL/SQL wrapping). Order: CREATE TABLE → COMMENT ON TABLE → COMMENT ON COLUMN
        /// (per field with non-empty caption) → CREATE INDEX (per non-PK index). The
        /// rebuild builder reuses this list to assemble its own block.
        /// </summary>
        internal IReadOnlyList<string> BuildRawStatements()
        {
            string tableName = this.TableSchema.TableName;
            var autoIncrementField = GetAutoIncrementField();
            string fields = GetFieldsCommandText(autoIncrementField);
            string primaryKey = GetPrimaryKeyCommandText(tableName, autoIncrementField);

            var list = new List<string>();

            var sb = new StringBuilder();
            sb.Append(CultureInfo.InvariantCulture, $"CREATE TABLE {OracleSchemaSyntax.QuoteName(tableName)} (\r\n{fields}");
            if (StringUtilities.IsNotEmpty(primaryKey))
                sb.Append(CultureInfo.InvariantCulture, $",\r\n  {primaryKey}");
            sb.Append("\r\n)");
            list.Add(sb.ToString());

            string tableComment = GetTableCommentStatementInternal(tableName);
            if (StringUtilities.IsNotEmpty(tableComment)) list.Add(tableComment);

            foreach (DbField field in this.TableSchema.Fields!)
            {
                string commentStmt = OracleSchemaSyntax.GetCommentStatement(tableName, field);
                if (StringUtilities.IsNotEmpty(commentStmt)) list.Add(commentStmt);
            }

            foreach (DbTableIndex index in this.TableSchema.Indexes!.Where(i => !i.PrimaryKey))
            {
                list.Add(BuildIndexStatement(tableName, index));
            }

            return list;
        }

        /// <summary>
        /// Gets the AutoIncrement field if the schema contains exactly one; null otherwise.
        /// Throws when multiple AutoIncrement fields are present (Oracle allows at most one
        /// IDENTITY column per table).
        /// </summary>
        private DbField? GetAutoIncrementField()
        {
            var autoIncrementFields = this.TableSchema.Fields!
                .Where(f => f.DbType == FieldDbType.AutoIncrement)
                .ToList();

            if (autoIncrementFields.Count == 0) return null;
            if (autoIncrementFields.Count > 1)
                throw new InvalidOperationException(
                    $"On Oracle, table '{TableSchema.TableName}' declares {autoIncrementFields.Count} AutoIncrement fields. "
                    + "Oracle supports at most one IDENTITY column per table.");

            return autoIncrementFields[0];
        }

        /// <summary>
        /// Validates the convention that an AutoIncrement field, if a primary key is declared,
        /// is the single-column primary key. Mirrors the constraint enforced by the MySQL and
        /// SQLite builders so AutoIncrement schemas behave consistently across providers.
        /// </summary>
        private void ValidateAutoIncrement()
        {
            var autoIncrementField = GetAutoIncrementField();
            if (autoIncrementField == null) return;

            var primaryKey = this.TableSchema.GetPrimaryKey();
            if (primaryKey == null) return;

            if (primaryKey.IndexFields!.Count != 1
                || !StringUtilities.IsEquals(primaryKey.IndexFields[0].FieldName, autoIncrementField.FieldName))
            {
                throw new InvalidOperationException(
                    $"On Oracle, AutoIncrement field '{autoIncrementField.FieldName}' must be the single-column primary key. "
                    + "Either restructure the schema or use FieldDbType.Long instead.");
            }
        }

        /// <summary>
        /// Builds a single CREATE INDEX statement (no trailing semicolon).
        /// </summary>
        private static string BuildIndexStatement(string tableName, DbTableIndex index)
        {
            string name = StringUtilities.Format(index.Name, tableName);
            var fieldBuilder = new StringBuilder();
            foreach (IndexField field in index.IndexFields!)
            {
                if (fieldBuilder.Length > 0)
                    fieldBuilder.Append(", ");
                fieldBuilder.Append(CultureInfo.InvariantCulture,
                    $"{OracleSchemaSyntax.QuoteName(field.FieldName)} {field.SortDirection.ToString().ToUpperInvariant()}");
            }
            string uniqueClause = index.Unique ? "UNIQUE " : string.Empty;
            return $"CREATE {uniqueClause}INDEX {OracleSchemaSyntax.QuoteName(name)} ON {OracleSchemaSyntax.QuoteName(tableName)} ({fieldBuilder})";
        }

        /// <summary>
        /// Gets the SQL fragment for all column definitions. The AutoIncrement column is
        /// emitted with the Oracle <c>GENERATED BY DEFAULT AS IDENTITY</c> form via
        /// <see cref="OracleSchemaSyntax.GetAutoIncrementColumnDefinition"/>.
        /// </summary>
        private string GetFieldsCommandText(DbField? autoIncrementField)
        {
            var sb = new StringBuilder();
            foreach (DbField field in this.TableSchema.Fields!)
            {
                if (sb.Length > 0)
                    sb.Append(",\r\n");
                if (autoIncrementField != null && field == autoIncrementField)
                    sb.Append("  " + OracleSchemaSyntax.GetAutoIncrementColumnDefinition(field));
                else
                    sb.Append("  " + OracleSchemaSyntax.GetColumnDefinition(field));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Gets the table-level PRIMARY KEY constraint SQL fragment. Oracle does not allow
        /// inline column-level PK, so the constraint is emitted in-line with the CREATE TABLE
        /// for both AutoIncrement and non-AutoIncrement schemas.
        /// </summary>
        /// <param name="tableName">The table name.</param>
        /// <param name="autoIncrementField">The AutoIncrement field, if any.</param>
        private string GetPrimaryKeyCommandText(string tableName, DbField? autoIncrementField)
        {
            var index = this.TableSchema.GetPrimaryKey();
            // When the schema has no declared PK but defines an AutoIncrement field, treat
            // that column as the implicit single-column PK (consistent with MySQL/SQLite).
            if (index == null && autoIncrementField == null) return string.Empty;

            string[] pkFieldNames;
            string pkConstraintNamePattern;
            if (index != null)
            {
                pkFieldNames = index.IndexFields!.Select(f => f.FieldName).ToArray();
                pkConstraintNamePattern = index.Name;
            }
            else
            {
                pkFieldNames = new[] { autoIncrementField!.FieldName };
                pkConstraintNamePattern = "pk_{0}";
            }

            var fieldBuilder = new StringBuilder();
            foreach (var fieldName in pkFieldNames)
            {
                if (fieldBuilder.Length > 0)
                    fieldBuilder.Append(", ");
                fieldBuilder.Append(OracleSchemaSyntax.QuoteName(fieldName));
            }

            string name = StringUtilities.Format(pkConstraintNamePattern, tableName);
            return $"CONSTRAINT {OracleSchemaSyntax.QuoteName(name)} PRIMARY KEY ({fieldBuilder})";
        }

        /// <summary>
        /// Gets the <c>COMMENT ON TABLE</c> statement when the schema has a non-empty
        /// <see cref="TableSchema.DisplayName"/>; otherwise empty. The schema reader
        /// round-trips the table caption from <c>USER_TAB_COMMENTS</c>, so emitting this
        /// here keeps fixture re-runs idempotent. No trailing semicolon — the caller wraps
        /// the statement inside <c>EXECUTE IMMEDIATE</c>.
        /// </summary>
        private string GetTableCommentStatementInternal(string tableName)
        {
            if (StringUtilities.IsEmpty(TableSchema.DisplayName))
                return string.Empty;

            return OracleSchemaSyntax.GetTableCommentStatement(tableName, this.TableSchema.DisplayName);
        }
    }
}
