using Polhem.Base.Data;
using Polhem.Definition.Database;

namespace Polhem.Db.Providers.Oracle
{
    /// <summary>
    /// Converts <see cref="FieldDbType"/> to Oracle 19c+ column type expressions.
    /// </summary>
    /// <remarks>
    /// Type choices:
    /// <list type="bullet">
    /// <item><see cref="FieldDbType.String"/> → <c>VARCHAR2(n CHAR)</c> when length is in
    ///       <c>1..4000</c>; otherwise <c>CLOB</c>. The 4000-byte VARCHAR2 ceiling is the
    ///       standard limit; <c>MAX_STRING_SIZE=EXTENDED</c> is intentionally not relied on.</item>
    /// <item><see cref="FieldDbType.Text"/> → <c>CLOB</c></item>
    /// <item><see cref="FieldDbType.Boolean"/> → <c>NUMBER(1)</c> (19c lacks a native BOOLEAN)</item>
    /// <item><see cref="FieldDbType.AutoIncrement"/> → <c>NUMBER(19)</c>; the
    ///       <c>GENERATED BY DEFAULT AS IDENTITY</c> clause is emitted by the CREATE TABLE builder</item>
    /// <item><see cref="FieldDbType.Short"/> → <c>NUMBER(5)</c>,
    ///       <see cref="FieldDbType.Integer"/> → <c>NUMBER(10)</c>,
    ///       <see cref="FieldDbType.Long"/> → <c>NUMBER(19)</c></item>
    /// <item><see cref="FieldDbType.Decimal"/> → <c>NUMBER(p,s)</c></item>
    /// <item><see cref="FieldDbType.Currency"/> → <c>NUMBER(19,4)</c></item>
    /// <item><see cref="FieldDbType.Date"/> → <c>DATE</c> (Oracle DATE includes second precision)</item>
    /// <item><see cref="FieldDbType.DateTime"/> → <c>TIMESTAMP(6)</c></item>
    /// <item><see cref="FieldDbType.Guid"/> → <c>RAW(16)</c> (aligns with <c>SYS_GUID()</c>'s native form)</item>
    /// <item><see cref="FieldDbType.Binary"/> → <c>BLOB</c></item>
    /// </list>
    /// </remarks>
    internal static class OracleTypeMapping
    {
        /// <summary>
        /// Standard VARCHAR2 byte ceiling on Oracle 19c+ when <c>MAX_STRING_SIZE=STANDARD</c>.
        /// String fields with <c>Length</c> outside <c>1..VarcharMaxLength</c> map to <c>CLOB</c>.
        /// </summary>
        private const int VarcharMaxLength = 4000;

        /// <summary>
        /// Determines whether the field maps to an Oracle LOB column (<c>CLOB</c> or <c>BLOB</c>).
        /// Derived from <see cref="GetOracleType(DbField)"/> so the two cannot drift apart — note a
        /// <see cref="FieldDbType.String"/> field is a LOB too once its length leaves the VARCHAR2 range.
        /// </summary>
        /// <param name="field">The field definition.</param>
        public static bool IsLobType(DbField field)
        {
            string dbType = GetOracleType(field);
            return string.Equals(dbType, "CLOB", StringComparison.Ordinal)
                || string.Equals(dbType, "BLOB", StringComparison.Ordinal);
        }

        /// <summary>
        /// Returns the Oracle column type expression for the given field definition.
        /// </summary>
        /// <param name="field">The field definition.</param>
        public static string GetOracleType(DbField field)
        {
            switch (field.DbType)
            {
                case FieldDbType.String:
                    return field.Length > 0 && field.Length <= VarcharMaxLength
                        ? $"VARCHAR2({field.Length} CHAR)"
                        : "CLOB";
                case FieldDbType.Text:
                    return "CLOB";
                case FieldDbType.Time:
                    return "VARCHAR2(5)";
                case FieldDbType.Boolean:
                    return "NUMBER(1)";
                case FieldDbType.AutoIncrement:
                    return "NUMBER(19)";
                case FieldDbType.Short:
                    return "NUMBER(5)";
                case FieldDbType.Integer:
                    return "NUMBER(10)";
                case FieldDbType.Long:
                    return "NUMBER(19)";
                case FieldDbType.Decimal:
                    {
                        int precision = field.Precision > 0 ? field.Precision : 18;
                        int scale = field.Scale > 0 ? field.Scale : 0;
                        return $"NUMBER({precision},{scale})";
                    }
                case FieldDbType.Currency:
                    return "NUMBER(19,4)";
                case FieldDbType.Date:
                    return "DATE";
                case FieldDbType.DateTime:
                    return "TIMESTAMP(6)";
                case FieldDbType.Guid:
                    return "RAW(16)";
                case FieldDbType.Binary:
                    return "BLOB";
                default:
                    throw new InvalidOperationException($"DbType={field.DbType} is not supported");
            }
        }
    }
}
