using System.Security.Cryptography;

namespace Polhem.Core.Security
{
    /// <summary>
    /// Hashes and verifies the secret segment of an API key, using a salted single-pass SHA-256.
    /// Stored form: <c>v1.{saltBase64}.{hashBase64}</c>.
    /// </summary>
    /// <remarks>
    /// IMPORTANT: this deliberately does NOT use <see cref="PasswordHasher"/>, and must not be
    /// "unified" with it. That type is PBKDF2 with <see cref="PasswordHasher.Iterations"/> iterations,
    /// which is correct for human-chosen, low-entropy passwords precisely because it is slow. An API key
    /// is verified on every single request, so putting that cost on this path would build a
    /// self-inflicted denial-of-service surface. The cost buys nothing here either: the secret is
    /// generated by the framework as 256 bits of cryptographic randomness, so the guessing attack a
    /// slow key-derivation function defends against does not exist.
    /// <para>
    /// NOTE: the salt is kept for format symmetry with <see cref="PasswordHasher"/> and to rule out
    /// collisions between identical secrets. It is not a security requirement at this entropy — a
    /// salt defends against rainbow tables and shared weak passwords, neither of which applies to a
    /// 256-bit random value. Equally, its presence does not give this scheme key-derivation
    /// strength; the strength comes from the secret's entropy.
    /// </para>
    /// <para>
    /// A server-side pepper was considered and rejected: it would tie every stored hash to the
    /// master key, so rotating that key would invalidate every issued API key, in exchange for
    /// offline-guessing resistance that a 256-bit secret does not need.
    /// </para>
    /// </remarks>
    public static class ApiKeyHasher
    {
        private const int SaltSize = 16; // 128-bit
        private const string V1Prefix = "v1.";

        /// <summary>
        /// Hashes the secret segment of an API key.
        /// </summary>
        /// <param name="secret">The plaintext secret segment.</param>
        /// <returns>The stored form, <c>v1.{saltBase64}.{hashBase64}</c>.</returns>
        public static string HashSecret(string secret)
        {
            ArgumentNullException.ThrowIfNull(secret);

            var salt = RandomNumberGenerator.GetBytes(SaltSize);
            var hash = ComputeHash(secret, salt);
            return $"{V1Prefix}{Convert.ToBase64String(salt)}.{Convert.ToBase64String(hash)}";
        }

        /// <summary>
        /// Verifies a plaintext secret against its stored hash, in constant time.
        /// </summary>
        /// <param name="secret">The plaintext secret segment supplied by the caller.</param>
        /// <param name="hashedSecret">The stored hash, as produced by <see cref="HashSecret"/>.</param>
        /// <returns><c>true</c> when the secret matches; otherwise, <c>false</c>.</returns>
        public static bool VerifySecret(string? secret, string? hashedSecret)
        {
            if (string.IsNullOrEmpty(secret) || string.IsNullOrEmpty(hashedSecret))
                return false;
            if (!hashedSecret.StartsWith(V1Prefix, StringComparison.Ordinal))
                return false;

            var parts = hashedSecret.Substring(V1Prefix.Length).Split('.');
            if (parts.Length != 2)
                return false;

            try
            {
                byte[] salt = Convert.FromBase64String(parts[0]);
                byte[] storedHash = Convert.FromBase64String(parts[1]);
                var computedHash = ComputeHash(secret, salt);
                return CryptographicOperations.FixedTimeEquals(storedHash, computedHash);
            }
            catch (FormatException)
            {
                // A malformed stored hash cannot be matched by any secret, so fail closed rather
                // than surfacing a storage problem as an authorization error.
                return false;
            }
        }

        /// <summary>
        /// Computes <c>SHA-256(salt || secret)</c>.
        /// </summary>
        /// <param name="secret">The plaintext secret segment.</param>
        /// <param name="salt">The salt bytes.</param>
        private static byte[] ComputeHash(string secret, byte[] salt)
        {
            var secretBytes = System.Text.Encoding.UTF8.GetBytes(secret);
            var buffer = new byte[salt.Length + secretBytes.Length];
            Buffer.BlockCopy(salt, 0, buffer, 0, salt.Length);
            Buffer.BlockCopy(secretBytes, 0, buffer, salt.Length, secretBytes.Length);
            return SHA256.HashData(buffer);
        }
    }
}
