using System.ComponentModel;
using System.Data;
using System.Globalization;
using Polhem.Base;
using Polhem.Base.Data;
using Polhem.Db.Dml;
using Polhem.Db.Providers.Oracle;
using Polhem.Tests.Shared;
using Polhem.Definition;
using Polhem.Definition.Database;
using Polhem.Definition.Filters;
using Polhem.Definition.Forms;
using Polhem.Definition.Storage;
using Polhem.Db.Manager;
using Polhem.Db.Schema;
using Polhem.Db.Schema.Changes;

namespace Polhem.Db.UnitTests
{
    /// <summary>
    /// Oracle-specific integration tests: schema reader round-trip against the live fixture
    /// table, session-level case-insensitive comparison provided by the connection-open hook
    /// (<c>ALTER SESSION SET NLS_COMP='LINGUISTIC' NLS_SORT='BINARY_CI'</c>), and end-to-end
    /// verification that framework-generated SQL runs against quoted-lowercase tables (since
    /// Oracle uppercases unquoted identifiers and the framework's identifier-quoting strategy
    /// is the only thing keeping <c>"st_user"</c>-style tables addressable). Skipped when no
    /// Oracle connection string is configured (<see cref="DbFactAttribute"/> handles the
    /// env-var check).
    /// </summary>
    public class OracleIntegrationTests : IClassFixture<SharedDbFixture>
    {
        private readonly SharedDbFixture _fx;

        public OracleIntegrationTests(SharedDbFixture fx) { _fx = fx; }
        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle SchemaProvider 應讀回 fixture 建好的 st_user 表")]
        public void SchemaProvider_ReadsFixtureTable()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var provider = new Polhem.Db.Providers.Oracle.OracleTableSchemaProvider(databaseId, _fx.GetRequiredService<IDbConnectionManager>());

            var schema = provider.GetTableSchema("st_user");

            Assert.NotNull(schema);
            Assert.Equal("st_user", schema!.TableName);
            // sys_no is NUMBER(19) GENERATED BY DEFAULT AS IDENTITY — read back as AutoIncrement.
            Assert.True(schema.Fields!.Contains("sys_no"));
            Assert.Equal(FieldDbType.AutoIncrement, schema.Fields["sys_no"].DbType);
            Assert.True(schema.Fields.Contains("sys_rowid"));
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle SchemaProvider 應對不存在的表回傳 null")]
        public void SchemaProvider_UnknownTable_ReturnsNull()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var provider = new Polhem.Db.Providers.Oracle.OracleTableSchemaProvider(databaseId, _fx.GetRequiredService<IDbConnectionManager>());

            var schema = provider.GetTableSchema("__no_such_table__");

            Assert.Null(schema);
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle 文字欄位字串比對應為 case-insensitive（session NLS_COMP=LINGUISTIC + NLS_SORT=BINARY_CI）")]
        public void StringComparison_IsCaseInsensitive()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var dbAccess = _fx.NewDbAccess(databaseId);

            // 手寫 minimal DDL 以聚焦於驗證 Oracle 對 session-level NLS 的執行行為，
            // 與 OracleCreateTableCommandBuilder 純語法測試獨立。Oracle 無 DROP TABLE
            // IF EXISTS，改用 PL/SQL block + 吞 ORA-00942。
            string dropDdl =
                "BEGIN " +
                "  EXECUTE IMMEDIATE 'DROP TABLE \"CI_TEST\" CASCADE CONSTRAINTS'; " +
                "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; " +
                "END;";

            dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.NonQuery, dropDdl));
            dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.NonQuery,
                "CREATE TABLE \"CI_TEST\" (\"NAME\" VARCHAR2(50 CHAR) NOT NULL)"));

            try
            {
                dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.NonQuery,
                    "INSERT INTO \"CI_TEST\" (\"NAME\") VALUES ({0})", "Jeff"));

                var result = dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.Scalar,
                    "SELECT COUNT(*) FROM \"CI_TEST\" WHERE \"NAME\" = {0}", "jeff"));

                Assert.NotNull(result);
                Assert.Equal(1, Convert.ToInt32(result.Scalar!, CultureInfo.InvariantCulture));
            }
            finally
            {
                dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.NonQuery, dropDdl));
            }
        }

        // ---------- quoted-lowercase end-to-end coverage ----------

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("FormSchema 驅動的 INSERT/SELECT/UPDATE/DELETE 應在 quoted-lowercase 表上正確運作")]
        public void FormCrud_QuotedLowercaseTable_InsertSelectUpdateDelete_Succeeds()
        {
            const string tableName = "tb_it_crud";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                CreateTable(dbAccess, BuildCrudTableSchema(tableName));

                var formSchema = BuildCrudFormSchema(tableName);
                var formBuilder = new OracleFormCommandBuilder(formSchema, _fx.GetRequiredService<IDefineAccess>());
                var rowId = Guid.NewGuid();

                // INSERT
                var insertRow = NewRow(formSchema, tableName, rowId, "alice", 10);
                int inserted = dbAccess.Execute(new InsertCommandBuilder(formSchema, DatabaseType.Oracle).Build("Foo", insertRow)).RowsAffected;
                Assert.Equal(1, inserted);

                // SELECT 驗證 INSERT 落地（含 WHERE rowId 等值）
                var selectByRowId = formBuilder.BuildSelect("Foo", "name,qty",
                    FilterCondition.Equal(SysFields.RowId, rowId), null);
                var selectResult = dbAccess.Execute(selectByRowId);
                Assert.NotNull(selectResult.Table);
                Assert.Single(selectResult.Table!.Rows);
                Assert.Equal("alice", selectResult.Table.Rows[0]["name"]);
                Assert.Equal(10, Convert.ToInt32(selectResult.Table.Rows[0]["qty"], CultureInfo.InvariantCulture));

                // UPDATE
                var updateRow = ExistingRow(formSchema, tableName, rowId, "alice", 10);
                updateRow["name"] = "alice2";
                updateRow["qty"] = 99;
                int updated = dbAccess.Execute(new UpdateCommandBuilder(formSchema, DatabaseType.Oracle).Build("Foo", updateRow)).RowsAffected;
                Assert.Equal(1, updated);

                var afterUpdate = dbAccess.Execute(selectByRowId);
                Assert.Equal("alice2", afterUpdate.Table!.Rows[0]["name"]);
                Assert.Equal(99, Convert.ToInt32(afterUpdate.Table.Rows[0]["qty"], CultureInfo.InvariantCulture));

                // DELETE
                int deleted = dbAccess.Execute(
                    formBuilder.BuildDelete("Foo", FilterCondition.Equal(SysFields.RowId, rowId))).RowsAffected;
                Assert.Equal(1, deleted);

                var afterDelete = dbAccess.Execute(selectByRowId);
                Assert.Empty(afterDelete.Table!.Rows);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("FromBuilder 產生的 JOIN 子句應在 quoted-lowercase 兩表 + ON 兩端欄位上可執行")]
        public void Join_QuotedLowercaseTables_FromBuilderEmitsExecutableSql()
        {
            const string masterTable = "tb_it_master";
            const string detailTable = "tb_it_detail";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, detailTable);
            DropQuotedTable(dbAccess, masterTable);

            try
            {
                CreateTable(dbAccess, BuildMasterSchema(masterTable));
                CreateTable(dbAccess, BuildDetailSchema(detailTable));

                var masterId = Guid.NewGuid();
                dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery,
                    "INSERT INTO \"TB_IT_MASTER\" (\"SYS_ROWID\", \"NAME\") VALUES ({0}, {1})",
                    masterId, "M1"));
                dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery,
                    "INSERT INTO \"TB_IT_DETAIL\" (\"SYS_ROWID\", \"MASTER_ID\", \"AMOUNT\") VALUES ({0}, {1}, {2})",
                    Guid.NewGuid(), masterId, 250));

                // 直接驅動 FromBuilder（FormSchema RelationField 路徑需 cross-form
                // DefinePath 設定，超出 quoting 驗證範圍；此處聚焦在 FromBuilder 對
                // join 兩端 table + ON 兩端 field 是否正確 quote）。
                var joins = new TableJoinCollection
                {
                    new TableJoin
                    {
                        Key = "j1",
                        JoinType = JoinType.Inner,
                        LeftAlias = "A",
                        LeftField = SysFields.RowId,
                        RightTable = detailTable,
                        RightAlias = "B",
                        RightField = "master_id",
                    },
                };

                string fromClause = new FromBuilder(DatabaseType.Oracle).Build(masterTable, joins);

                // FromBuilder 產出片段必含完整雙引號識別符（撞到 ORA-00942 / ORA-00904
                // 的常見漏洞點）。
                Assert.Contains("FROM \"TB_IT_MASTER\" A", fromClause);
                Assert.Contains("INNER JOIN \"TB_IT_DETAIL\" B", fromClause);
                Assert.Contains("A.\"SYS_ROWID\" = B.\"MASTER_ID\"", fromClause);

                var spec = new DbCommandSpec(DbCommandKind.DataTable,
                    $"SELECT A.\"NAME\", B.\"AMOUNT\" {fromClause} WHERE A.\"SYS_ROWID\" = {{0}}",
                    masterId);
                var result = dbAccess.Execute(spec);

                Assert.NotNull(result.Table);
                Assert.Single(result.Table!.Rows);
                Assert.Equal("M1", result.Table.Rows[0]["name"]);
                Assert.Equal(250, Convert.ToInt32(result.Table.Rows[0]["amount"], CultureInfo.InvariantCulture));
            }
            finally
            {
                DropQuotedTable(dbAccess, detailTable);
                DropQuotedTable(dbAccess, masterTable);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle reserved word 命名的欄位（comment / order）quoted 後應可 CRUD")]
        public void ReservedWordFieldName_QuotedLowercase_CrudSucceeds()
        {
            const string tableName = "tb_it_reserved";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                // "comment" 與 "order" 皆為 Oracle reserved word；少一邊雙引號就會
                // 直接 syntax error，是 quoting 機制的剛性需求驗證。
                var schema = new TableSchema { TableName = tableName };
                schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                schema.Fields!.Add("comment", "Comment", FieldDbType.String, 100);
                schema.Fields!.Add("order", "Order", FieldDbType.Integer);
                schema.Indexes!.AddPrimaryKey(SysFields.RowId);
                CreateTable(dbAccess, schema);

                var formSchema = new FormSchema("X", "X");
                var table = formSchema.Tables!.Add("Foo", "Foo");
                table.DbTableName = tableName;
                table.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                table.Fields!.AddStringField("comment", "Comment", 100);
                table.Fields!.Add("order", "Order", FieldDbType.Integer);

                var formBuilder = new OracleFormCommandBuilder(formSchema, _fx.GetRequiredService<IDefineAccess>());
                var rowId = Guid.NewGuid();

                var insertRow = NewRow(formSchema, tableName, rowId);
                insertRow["comment"] = "hello";
                insertRow["order"] = 7;
                dbAccess.Execute(new InsertCommandBuilder(formSchema, DatabaseType.Oracle).Build("Foo", insertRow));

                var selected = dbAccess.Execute(formBuilder.BuildSelect("Foo", "comment,order",
                    FilterCondition.Equal("order", 7), null));
                Assert.NotNull(selected.Table);
                Assert.Single(selected.Table!.Rows);
                Assert.Equal("hello", selected.Table.Rows[0]["comment"]);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("OracleTableAlterCommandBuilder.ADD column 應能在 quoted-lowercase 表上執行並保留資料")]
        public void AlterAddColumn_QuotedLowercaseTable_Succeeds()
        {
            // Rebuild 路徑（OracleTableRebuildCommandBuilder.GetCommandText）目前回傳混合
            // PL/SQL block + 純 SQL 的多語句腳本，Oracle.ManagedDataAccess 一次只能執行一條，
            // 整個腳本需在呼叫端拆分後逐條送出，或由 builder API 改為 GetStatements()。此測試
            // 因此只覆蓋 Alter（已採 GetStatements 模式），Rebuild 端到端驗證留待後續另案。
            const string tableName = "tb_it_alter";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                var initial = new TableSchema { TableName = tableName };
                initial.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                initial.Fields!.Add("name", "Name", FieldDbType.String, 50);
                initial.Indexes!.AddPrimaryKey(SysFields.RowId);
                CreateTable(dbAccess, initial);

                var rowId = Guid.NewGuid();
                dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery,
                    "INSERT INTO \"TB_IT_ALTER\" (\"SYS_ROWID\", \"NAME\") VALUES ({0}, {1})",
                    rowId, "before"));

                var alterBuilder = new OracleTableAlterCommandBuilder();
                var addStatements = alterBuilder.GetStatements(tableName,
                    new Polhem.Db.Schema.Changes.AddFieldChange(
                        new DbField("age", "Age", FieldDbType.Integer) { AllowNull = true }));
                foreach (var stmt in addStatements)
                {
                    dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery, stmt));
                }

                var provider = new OracleTableSchemaProvider(TestDbConventions.GetDatabaseId(DatabaseType.Oracle), _fx.GetRequiredService<IDbConnectionManager>());
                var afterAlter = provider.GetTableSchema(tableName);
                Assert.NotNull(afterAlter);
                Assert.True(afterAlter!.Fields!.Contains("age"));

                var preserved = dbAccess.Execute(new DbCommandSpec(DbCommandKind.Scalar,
                    "SELECT \"NAME\" FROM \"TB_IT_ALTER\" WHERE \"SYS_ROWID\" = {0}", rowId));
                Assert.Equal("before", preserved.Scalar);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("OracleTableAlterCommandBuilder.MODIFY 對既有 NOT NULL 欄（nullability 未變）不應拋 ORA-01442")]
        public void AlterModify_RedundantNotNull_QuotedLowercaseTable_DoesNotRaiseOra01442()
        {
            const string tableName = "tb_it_modnull";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                // 建一張帶非字串 NOT NULL 欄的表（qty 預設 AllowNull=false → NUMBER(10) DEFAULT 0 NOT NULL）。
                var initial = new TableSchema { TableName = tableName };
                initial.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                initial.Fields!.Add("qty", "Qty", FieldDbType.Integer);
                initial.Indexes!.AddPrimaryKey(SysFields.RowId);
                CreateTable(dbAccess, initial);

                // 對既有 NOT NULL 的 qty 做 ALTER：nullability 不變、僅 default 0 → 1。
                // 修正前 builder 會重發 MODIFY (... NOT NULL) → 對已 NOT NULL 欄拋 ORA-01442；
                // 修正後省略冗餘 nullability hint，MODIFY 應成功執行。
                var oldField = new DbField("qty", "Qty", FieldDbType.Integer) { AllowNull = false, DefaultValue = "0" };
                var newField = new DbField("qty", "Qty", FieldDbType.Integer) { AllowNull = false, DefaultValue = "1" };
                var statements = new OracleTableAlterCommandBuilder()
                    .GetStatements(tableName, new Polhem.Db.Schema.Changes.AlterFieldChange(oldField, newField));

                var ex = Record.Exception(() =>
                {
                    foreach (var stmt in statements)
                        dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery, stmt));
                });

                Assert.Null(ex);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("AllowNull=false 的 String 欄在 Oracle 建為 nullable：省略該欄 INSERT 成功、讀回空字串、且二次 diff 為空")]
        public void NonNullString_OracleNullable_OmittedInsertSucceedsAndDiffIsEmpty()
        {
            const string tableName = "tb_it_strnull";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                // definition 仍標 AllowNull=false（語意上「不該是 null」）；customize_id 場景的縮影。
                var define = new TableSchema { TableName = tableName };
                define.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                define.Fields!.Add("customize_id", "Customize", FieldDbType.String, 50);
                define.Indexes!.AddPrimaryKey(SysFields.RowId);
                CreateTable(dbAccess, define);

                // 省略 customize_id 的 INSERT 不應拋 ORA-01400（欄位已建為 nullable）。
                var rowId = Guid.NewGuid();
                var insert = Record.Exception(() => dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery,
                    "INSERT INTO \"TB_IT_STRNULL\" (\"SYS_ROWID\") VALUES ({0})", rowId)));
                Assert.Null(insert);

                // 讀回的 customize_id 是 Oracle NULL，經 ValueUtilities.CStr 正規化為空字串。
                var read = dbAccess.Execute(new DbCommandSpec(DbCommandKind.Scalar,
                    "SELECT \"CUSTOMIZE_ID\" FROM \"TB_IT_STRNULL\" WHERE \"SYS_ROWID\" = {0}", rowId));
                Assert.Equal(string.Empty, ValueUtilities.CStr(read.Scalar!));

                // 升級冪等性：讀回 schema 與 definition 比對，customize_id 欄不應產生差異
                // （provider 對 String/Text 一律回報 AllowNull=false 以對齊 definition）。
                var provider = new OracleTableSchemaProvider(
                    TestDbConventions.GetDatabaseId(DatabaseType.Oracle), _fx.GetRequiredService<IDbConnectionManager>());
                var real = provider.GetTableSchema(tableName);
                Assert.NotNull(real);
                var defineField = define.Fields!["customize_id"];
                var realField = real!.Fields![defineField.FieldName];
                Assert.False(realField.AllowNull);
                Assert.True(defineField.Compare(realField));
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle 升級：含 nullable Text 欄的表加欄應成功且冪等（迴歸 ORA-22859）")]
        public void Upgrade_TableWithNullableTextColumn_AddsColumnAndIsIdempotent()
        {
            const string tableName = "tb_it_lobupg";
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var connectionManager = _fx.GetRequiredService<IDbConnectionManager>();
            var dbAccess = _fx.NewDbAccess(databaseId);
            DropQuotedTable(dbAccess, tableName);

            try
            {
                // 建表：定義層對 Text 標 AllowNull=true，Oracle 實體一律建成 nullable CLOB。
                var initial = BuildLobUpgradeSchema(tableName, includeAddedColumn: false);
                CreateTable(dbAccess, initial);

                // 升級：多一個 String 欄。CLOB 欄本身沒變，不該被一起發 MODIFY。
                var define = BuildLobUpgradeSchema(tableName, includeAddedColumn: true);
                var provider = new OracleTableSchemaProvider(databaseId, connectionManager);
                var orchestrator = new TableUpgradeOrchestrator(new OracleDialectFactory(), connectionManager);

                var diff = new TableSchemaComparer(define, provider.GetTableSchema(tableName), DatabaseType.Oracle).CompareToDiff();
                var plan = orchestrator.Plan(diff);
                // CLOB 欄若被誤判為有差異，這裡會多出一筆 AlterColumns stage 並在 Execute 擲 ORA-22859。
                Assert.Equal(UpgradeExecutionMode.Alter, plan.Mode);
                var addChange = Assert.Single(diff.Changes);
                Assert.Equal("api_key_id", Assert.IsType<AddFieldChange>(addChange).Field.FieldName);

                orchestrator.Execute(plan, databaseId);

                var upgraded = provider.GetTableSchema(tableName);
                Assert.NotNull(upgraded);
                Assert.True(upgraded!.Fields!.Contains("api_key_id"));

                // 冪等性：第二輪比對不應再產生任何差異（否則每次啟動都重跑一次失敗的升級）。
                var secondDiff = new TableSchemaComparer(define, upgraded, DatabaseType.Oracle).CompareToDiff();
                Assert.Empty(secondDiff.Changes);
                // ALTER 加欄位的同一份 plan 也要把該欄的 caption 寫進 USER_COL_COMMENTS，
                // 否則 api_key_id 的 caption 永遠算一筆 DescriptionChange，diff 不會空，
                // 「這張表是不是最新的」永遠答否。
                Assert.Empty(secondDiff.DescriptionChanges);
                Assert.True(secondDiff.IsEmpty);
                Assert.Equal(UpgradeExecutionMode.NoChange, orchestrator.Plan(secondDiff).Mode);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        // ---------- helpers ----------

        private static TableSchema BuildLobUpgradeSchema(string tableName, bool includeAddedColumn)
        {
            var schema = new TableSchema { TableName = tableName };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields!.Add("user_id", "User", FieldDbType.String, 50).AllowNull = true;
            schema.Fields!.Add("error_message", "Message", FieldDbType.Text).AllowNull = true;
            if (includeAddedColumn)
                schema.Fields!.Add("api_key_id", "API Key", FieldDbType.String, 50).AllowNull = true;
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }


        private static TableSchema BuildCrudTableSchema(string tableName)
        {
            var schema = new TableSchema { TableName = tableName };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields!.Add("name", "Name", FieldDbType.String, 50);
            schema.Fields!.Add("qty", "Qty", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        private static FormSchema BuildCrudFormSchema(string tableName)
        {
            var schema = new FormSchema("X", "X");
            var table = schema.Tables!.Add("Foo", "Foo");
            table.DbTableName = tableName;
            table.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            table.Fields!.AddStringField("name", "Name", 50);
            table.Fields!.Add("qty", "Qty", FieldDbType.Integer);
            return schema;
        }

        private static TableSchema BuildMasterSchema(string tableName)
        {
            var schema = new TableSchema { TableName = tableName };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields!.Add("name", "Name", FieldDbType.String, 50);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        private static TableSchema BuildDetailSchema(string tableName)
        {
            var schema = new TableSchema { TableName = tableName };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields!.Add("master_id", "Master ID", FieldDbType.Guid);
            schema.Fields!.Add("amount", "Amount", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        private static DataRow NewRow(FormSchema formSchema, string tableName, Guid rowId, string? name = null, int? qty = null)
        {
            var dt = BuildDataTable(formSchema, tableName);
            var row = dt.NewRow();
            row[SysFields.RowId] = rowId;
            if (name != null) row["name"] = name;
            if (qty != null) row["qty"] = qty.Value;
            return row;
        }

        private static DataRow ExistingRow(FormSchema formSchema, string tableName, Guid rowId, string name, int qty)
        {
            // Update path 需要 row.RowState != Added；先 Add+AcceptChanges，後續欄位修改才會被
            // BuildUpdate 偵測為 modified。
            var dt = BuildDataTable(formSchema, tableName);
            var row = dt.NewRow();
            row[SysFields.RowId] = rowId;
            row["name"] = name;
            row["qty"] = qty;
            dt.Rows.Add(row);
            dt.AcceptChanges();
            return row;
        }

        private static DataTable BuildDataTable(FormSchema formSchema, string tableName)
        {
            var formTable = formSchema.Tables!["Foo"]!;
            var dt = new DataTable(tableName);
            foreach (var field in formTable.Fields!)
            {
                dt.Columns.Add(field.FieldName, MapClrType(field.DbType));
            }
            return dt;
        }

        private static Type MapClrType(FieldDbType dbType) => dbType switch
        {
            FieldDbType.Guid => typeof(Guid),
            FieldDbType.String => typeof(string),
            FieldDbType.Integer => typeof(int),
            FieldDbType.Long => typeof(long),
            FieldDbType.Decimal => typeof(decimal),
            FieldDbType.DateTime => typeof(DateTime),
            FieldDbType.Date => typeof(DateTime),
            FieldDbType.Boolean => typeof(bool),
            _ => typeof(object),
        };

        private static void CreateTable(DbAccess dbAccess, TableSchema schema)
        {
            string sql = new OracleCreateTableCommandBuilder().GetCommandText(schema);
            dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery, sql));
        }

        private static void DropQuotedTable(DbAccess dbAccess, string tableName)
        {
            // Oracle 無 DROP TABLE IF EXISTS；包 PL/SQL block 並吞 ORA-00942。
            // Framework 統一以 UPPERCASE 形式儲存於 Oracle（per OracleSchemaSyntax.QuoteName），
            // 此 helper 跨過 framework 直接拼 DDL，必須自行 UPPER 化以對齊。
            string storageName = tableName.ToUpperInvariant();
            string ddl =
                "BEGIN " +
                "  EXECUTE IMMEDIATE 'DROP TABLE \"" + storageName + "\" CASCADE CONSTRAINTS'; " +
                "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; " +
                "END;";
            dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery, ddl));
        }
    }
}
