using System.ComponentModel;
using Polhem.Base.Data;
using Polhem.Db.Providers.Oracle;
using Polhem.Definition;
using Polhem.Definition.Database;

namespace Polhem.Db.UnitTests
{
    /// <summary>
    /// Pure-syntax tests for <see cref="OracleCreateTableCommandBuilder"/>. No live database
    /// connection — the builder produces string output that is asserted via
    /// <see cref="Assert.Contains(string, string)"/> against the well-known fragments
    /// for Oracle 19c+ dialect (double-quote quoting, NUMBER 系列、VARCHAR2(n CHAR)、
    /// GENERATED BY DEFAULT AS IDENTITY、independent COMMENT ON statements).
    /// </summary>
    /// <remarks>
    /// All output is wrapped in a PL/SQL anonymous block so multiple DDL statements can
    /// be dispatched through Oracle.ManagedDataAccess in a single command. Inside the
    /// <c>EXECUTE IMMEDIATE</c> string literal, every single quote in the wrapped DDL is
    /// escaped to <c>''</c>; assertions on string-default and COMMENT fragments must
    /// account for this doubled-quote form.
    /// </remarks>
    public class OracleCreateTableCommandBuilderTests
    {
        private static TableSchema BuildSchema(FieldDbType dbType, int length = 0,
            int precision = 18, int scale = 0, bool allowNull = false, string defaultValue = "")
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            var field = schema.Fields.Add("col", "Col", dbType, length);
            field.Precision = precision;
            field.Scale = scale;
            field.AllowNull = allowNull;
            field.DefaultValue = defaultValue;
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        #region GetOracleType 各 FieldDbType 分支

        [Theory]
        [InlineData(FieldDbType.Boolean, "NUMBER(1)")]
        [InlineData(FieldDbType.Short, "NUMBER(5)")]
        [InlineData(FieldDbType.Integer, "NUMBER(10)")]
        [InlineData(FieldDbType.Long, "NUMBER(19)")]
        [InlineData(FieldDbType.Currency, "NUMBER(19,4)")]
        [InlineData(FieldDbType.Date, "DATE")]
        [InlineData(FieldDbType.DateTime, "TIMESTAMP(6)")]
        [InlineData(FieldDbType.Time, "VARCHAR2(5)")]
        [InlineData(FieldDbType.Guid, "RAW(16)")]
        [InlineData(FieldDbType.Binary, "BLOB")]
        [InlineData(FieldDbType.Text, "CLOB")]
        [DisplayName("GetCommandText 應為各 FieldDbType 產生對應的 Oracle 型別字串")]
        public void GetCommandText_FieldDbType_GeneratesCorrectColumnType(FieldDbType dbType, string expectedFragment)
        {
            var schema = BuildSchema(dbType);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains(expectedFragment, sql);
        }

        [Fact]
        [DisplayName("GetCommandText String 型別應使用 VARCHAR2(n CHAR) 並指定字元長度")]
        public void GetCommandText_String_UsesVarchar2CharSemantics()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // CHAR semantic 避免中文/多 byte 字元被截斷
            Assert.Contains("VARCHAR2(50 CHAR)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText String 長度超過 4000 byte 上限應改用 CLOB")]
        public void GetCommandText_StringOverVarcharLimit_FallsBackToClob()
        {
            var schema = BuildSchema(FieldDbType.String, length: 8000);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // VARCHAR2 標準上限 4000 byte；超過時退化為 CLOB 而非依賴 EXTENDED 模式
            Assert.Contains("\"COL\" CLOB", sql);
            Assert.DoesNotContain("VARCHAR2", sql);
        }

        [Fact]
        [DisplayName("GetCommandText String 長度為 0 應改用 CLOB")]
        public void GetCommandText_StringZeroLength_FallsBackToClob()
        {
            var schema = BuildSchema(FieldDbType.String, length: 0);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"COL\" CLOB", sql);
        }

        [Fact]
        [DisplayName("GetCommandText Decimal 應使用 NUMBER(precision,scale)")]
        public void GetCommandText_Decimal_UsesNumberPrecisionScale()
        {
            var schema = BuildSchema(FieldDbType.Decimal, precision: 12, scale: 3);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("NUMBER(12,3)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText 不支援的 FieldDbType 應擲出 InvalidOperationException")]
        public void GetCommandText_UnknownDbType_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("col", "Col", (FieldDbType)999);
            var builder = new OracleCreateTableCommandBuilder();

            Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
        }

        #endregion

        #region 識別符引用與表後綴

        [Fact]
        [DisplayName("識別符應以雙引號引用（Oracle reserved word 多，statically quote 為安全策略）")]
        public void GetCommandText_Identifiers_UseDoubleQuotes()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CREATE TABLE \"ST_DEMO\"", sql);
            Assert.Contains("\"COL\"", sql);
        }

        [Fact]
        [DisplayName("CREATE TABLE 不應帶 ENGINE / CHARSET / COLLATE 後綴（Oracle 走 DB 預設）")]
        public void GetCommandText_NoTableSuffix()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Oracle 採 session 級 NLS 設定（GlobalFixture ALTER SESSION）取代 column-level COLLATE
            Assert.DoesNotContain("ENGINE=", sql);
            Assert.DoesNotContain("CHARSET=", sql);
            Assert.DoesNotContain("COLLATE", sql);
        }

        [Fact]
        [DisplayName("含特殊字元（雙引號）的識別符應正確 escape")]
        public void GetCommandText_IdentifierWithDoubleQuote_IsEscaped()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields.Add("col\"x", "Col", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"COL\"\"X\"", sql);
        }

        #endregion

        #region Default Expressions

        [Fact]
        [DisplayName("非 AllowNull Integer 欄位應產生 DEFAULT 0 NOT NULL（Oracle 順序為 type DEFAULT NOT NULL）")]
        public void GetCommandText_NonNullInteger_GeneratesDefault0NotNull()
        {
            var schema = BuildSchema(FieldDbType.Integer, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"COL\" NUMBER(10) DEFAULT 0 NOT NULL", sql);
        }

        [Fact]
        [DisplayName("非 AllowNull String 欄位（無顯式預設值）應建為 nullable 且不帶 DEFAULT")]
        public void GetCommandText_NonNullString_EmitsNullableWithoutDefault()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Oracle 把 '' 視為 NULL，DEFAULT '' 即 DEFAULT NULL，與 NOT NULL 自相矛盾。
            // 故 definition AllowNull=false 的 String 欄一律建為 nullable、不帶 DEFAULT，
            // 由 C# 層 ValueUtilities.CStr(null)→"" 維持「永不為 null」語意。
            Assert.Contains("\"COL\" VARCHAR2(50 CHAR) NULL", sql);
            Assert.DoesNotContain("\"COL\" VARCHAR2(50 CHAR) DEFAULT", sql);
            Assert.DoesNotContain("\"COL\" VARCHAR2(50 CHAR) NOT NULL", sql);
        }

        [Fact]
        [DisplayName("AllowNull 欄位不應有 DEFAULT 子句")]
        public void GetCommandText_AllowNullField_OmitsDefault()
        {
            var schema = BuildSchema(FieldDbType.Integer, allowNull: true);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"COL\" NUMBER(10) NULL", sql);
            Assert.DoesNotContain("\"COL\" NUMBER(10) DEFAULT", sql);
        }

        [Fact]
        [DisplayName("Guid 欄位 DEFAULT 應為 SYS_GUID()")]
        public void GetCommandText_NonNullGuid_GeneratesSysGuidDefault()
        {
            var schema = BuildSchema(FieldDbType.Guid, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT SYS_GUID()", sql);
        }

        [Fact]
        [DisplayName("DateTime 欄位 DEFAULT 應為 SYS_EXTRACT_UTC(SYSTIMESTAMP)")]
        public void GetCommandText_NonNullDateTime_GeneratesSystimestampDefault()
        {
            var schema = BuildSchema(FieldDbType.DateTime, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)", sql);
        }

        [Fact]
        [DisplayName("Text 欄位（CLOB）應建為 nullable 且不帶 DEFAULT（同 String 的 '' == NULL 規則）")]
        public void GetCommandText_Text_EmitsNullableWithoutDefault()
        {
            var textSchema = new TableSchema { TableName = "st_demo" };
            textSchema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            textSchema.Fields.Add("note", "Note", FieldDbType.Text);
            textSchema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(textSchema);

            Assert.Contains("\"NOTE\" CLOB NULL", sql);
            Assert.DoesNotContain("\"NOTE\" CLOB DEFAULT", sql);
            Assert.DoesNotContain("\"NOTE\" CLOB NOT NULL", sql);
        }

        [Fact]
        [DisplayName("Binary 欄位（BLOB）即使 NOT NULL 也不應產生 DEFAULT（BLOB 限制）")]
        public void GetCommandText_Binary_OmitsDefault()
        {
            var binarySchema = new TableSchema { TableName = "st_demo" };
            binarySchema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            binarySchema.Fields.Add("blob", "Blob", FieldDbType.Binary);
            binarySchema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(binarySchema);

            Assert.Contains("\"BLOB\" BLOB NOT NULL", sql);
            Assert.DoesNotContain("\"BLOB\" BLOB DEFAULT", sql);
        }

        [Fact]
        [DisplayName("含單引號的 String DEFAULT 值經 PL/SQL 雙重 escape 後為 ''O''''Brien''")]
        public void GetCommandText_StringDefaultWithQuote_IsEscaped()
        {
            var schema = BuildSchema(FieldDbType.String, length: 20, defaultValue: "O'Brien");
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // 兩層 escape：原始 DEFAULT 'O''Brien' 在 PL/SQL EXECUTE IMMEDIATE 字面內
            // 每個單引號再 escape 一次，最終單引號都成雙倍。
            Assert.Contains("DEFAULT ''O''''Brien''", sql);
        }

        #endregion

        #region AutoIncrement

        [Fact]
        [DisplayName("AutoIncrement 欄位應產生 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL")]
        public void GetCommandText_AutoIncrement_UsesIdentitySyntax()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            schema.Indexes!.AddPrimaryKey("sys_no");
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"SYS_NO\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
            // Oracle 不允許 inline column-level PRIMARY KEY，必為 table-level CONSTRAINT
            Assert.Contains("CONSTRAINT", sql);
            Assert.Contains("PRIMARY KEY (\"SYS_NO\")", sql);
        }

        [Fact]
        [DisplayName("AutoIncrement 欄位若非單欄 PK 應拋 InvalidOperationException")]
        public void GetCommandText_AutoIncrementNotSinglePk_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            schema.Fields!.Add("other", "Other", FieldDbType.String, 10);
            schema.Indexes!.AddPrimaryKey("other");

            var builder = new OracleCreateTableCommandBuilder();
            var ex = Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
            Assert.Contains("must be the single-column primary key", ex.Message);
        }

        [Fact]
        [DisplayName("無宣告 PK 但有 AutoIncrement 欄位應自動以 pk_{表名} 為 PK constraint name")]
        public void GetCommandText_AutoIncrementWithoutDeclaredPk_UsesDefaultPkName()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            // 不在 Indexes 加 PK；由 builder 自動產生 PK constraint
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"SYS_NO\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
            Assert.Contains("CONSTRAINT \"PK_ST_DEMO\" PRIMARY KEY (\"SYS_NO\")", sql);
        }

        [Fact]
        [DisplayName("多個 AutoIncrement 欄位應拋 InvalidOperationException")]
        public void GetCommandText_MultipleAutoIncrement_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("a", "A", FieldDbType.AutoIncrement);
            schema.Fields!.Add("b", "B", FieldDbType.AutoIncrement);
            schema.Indexes!.AddPrimaryKey("a");

            var builder = new OracleCreateTableCommandBuilder();
            var ex = Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
            Assert.Contains("at most one IDENTITY", ex.Message);
        }

        #endregion

        #region PRIMARY KEY 與索引

        [Fact]
        [DisplayName("無 AutoIncrement 的 schema 應產生獨立 PRIMARY KEY constraint")]
        public void GetCommandText_NonAutoIncrementSchema_EmitsPrimaryKeyConstraint()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CONSTRAINT \"PK_ST_DEMO\" PRIMARY KEY (\"SYS_ROWID\")", sql);
        }

        [Fact]
        [DisplayName("PK constraint 不應帶 ASC/DESC 排序方向（Oracle 語法限制）")]
        public void GetCommandText_PrimaryKey_OmitsSortDirection()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Oracle 的 PRIMARY KEY constraint 內 column 不接受 ASC/DESC
            Assert.DoesNotContain("PRIMARY KEY (\"SYS_ROWID\" ASC)", sql);
            Assert.DoesNotContain("PRIMARY KEY (\"SYS_ROWID\" DESC)", sql);
        }

        [Fact]
        [DisplayName("非 PK 索引應產生 CREATE INDEX 語句並帶 ASC/DESC（包在 EXECUTE IMMEDIATE 內無 trailing semicolon）")]
        public void GetCommandText_NonPkIndexes_EmitCreateIndexStatements()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.Indexes!.Add("ix_{0}_col", "col", false);
            schema.Indexes!.Add("uk_{0}_col", "col", true);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("CREATE INDEX \"IX_ST_DEMO_COL\" ON \"ST_DEMO\" (\"COL\" ASC)", sql);
            Assert.Contains("CREATE UNIQUE INDEX \"UK_ST_DEMO_COL\" ON \"ST_DEMO\" (\"COL\" ASC)", sql);
        }

        #endregion

        #region COMMENT ON

        [Fact]
        [DisplayName("DisplayName 非空時應產生獨立 COMMENT ON TABLE 語句（PL/SQL escape 後 IS 後字串為 ''示範資料表''）")]
        public void GetCommandText_DisplayName_EmitsCommentOnTable()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "示範資料表";

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON TABLE \"ST_DEMO\" IS ''示範資料表''", sql);
        }

        [Fact]
        [DisplayName("DisplayName 為空時不應產生 COMMENT ON TABLE 語句")]
        public void GetCommandText_NoDisplayName_OmitsCommentOnTable()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.DoesNotContain("COMMENT ON TABLE", sql);
        }

        [Fact]
        [DisplayName("Caption 非空的欄位應產生對應 COMMENT ON COLUMN 語句（PL/SQL escape 後）")]
        public void GetCommandText_FieldCaption_EmitsCommentOnColumn()
        {
            var schema = BuildSchema(FieldDbType.Integer);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON COLUMN \"ST_DEMO\".\"SYS_ROWID\" IS ''Row ID''", sql);
            Assert.Contains("COMMENT ON COLUMN \"ST_DEMO\".\"COL\" IS ''Col''", sql);
        }

        [Fact]
        [DisplayName("Caption 含單引號經 PL/SQL 雙重 escape 後為 ''User''''s note''")]
        public void GetCommandText_CaptionWithQuote_IsEscaped()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields.Add("col", "User's note", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            // 兩層 escape：caption 'User''s note'（原 SQL）→ 在 PL/SQL EXECUTE IMMEDIATE 字面內
            // 每個單引號再 escape 一次。
            Assert.Contains("COMMENT ON COLUMN \"ST_DEMO\".\"COL\" IS ''User''''s note''", sql);
        }

        [Fact]
        [DisplayName("輸出整體應包成 PL/SQL anonymous block（BEGIN/END + EXECUTE IMMEDIATE）")]
        public void GetCommandText_WrapsInPlSqlBlock()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("BEGIN", sql);
            Assert.Contains("EXECUTE IMMEDIATE 'CREATE TABLE \"ST_DEMO\"", sql);
            Assert.EndsWith("END;", sql);
        }

        #endregion
    }
}
