using System.ComponentModel;
using System.Data;
using System.Globalization;
using Polhem.Base;
using Polhem.Base.Data;
using Polhem.Db.Dml;
using Polhem.Db.Providers.Oracle;
using Polhem.Tests.Shared;
using Polhem.Definition;
using Polhem.Definition.Database;
using Polhem.Definition.Filters;
using Polhem.Definition.Forms;
using Polhem.Definition.Storage;
using Polhem.Db.Manager;
using Polhem.Db.Schema;
using Polhem.Db.Schema.Changes;

namespace Polhem.Db.UnitTests
{
    /// <summary>
    /// Oracle-specific integration tests: schema reader round-trip against the live fixture
    /// table, session-level case-insensitive comparison provided by the connection-open hook
    /// (<c>ALTER SESSION SET NLS_COMP='LINGUISTIC' NLS_SORT='BINARY_CI'</c>), and end-to-end
    /// verification that framework-generated SQL runs against quoted-lowercase tables (since
    /// Oracle uppercases unquoted identifiers and the framework's identifier-quoting strategy
    /// is the only thing keeping <c>"st_user"</c>-style tables addressable). Skipped when no
    /// Oracle connection string is configured (<see cref="DbFactAttribute"/> handles the
    /// env-var check).
    /// </summary>
    public class OracleIntegrationTests : IClassFixture<SharedDbFixture>
    {
        private readonly SharedDbFixture _fx;

        public OracleIntegrationTests(SharedDbFixture fx) { _fx = fx; }
        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle SchemaProvider reads back the st_user table created by the fixture")]
        public void SchemaProvider_ReadsFixtureTable()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var provider = new Polhem.Db.Providers.Oracle.OracleTableSchemaProvider(databaseId, _fx.GetRequiredService<IDbConnectionManager>());

            var schema = provider.GetTableSchema("st_user");

            Assert.NotNull(schema);
            Assert.Equal("st_user", schema!.TableName);
            // sys_no is NUMBER(19) GENERATED BY DEFAULT AS IDENTITY — read back as AutoIncrement.
            Assert.True(schema.Fields!.Contains("sys_no"));
            Assert.Equal(FieldDbType.AutoIncrement, schema.Fields["sys_no"].DbType);
            Assert.True(schema.Fields.Contains("sys_rowid"));
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle SchemaProvider returns null for a table that does not exist")]
        public void SchemaProvider_UnknownTable_ReturnsNull()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var provider = new Polhem.Db.Providers.Oracle.OracleTableSchemaProvider(databaseId, _fx.GetRequiredService<IDbConnectionManager>());

            var schema = provider.GetTableSchema("__no_such_table__");

            Assert.Null(schema);
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle compares text columns case-insensitively (session NLS_COMP=LINGUISTIC + NLS_SORT=BINARY_CI)")]
        public void StringComparison_IsCaseInsensitive()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var dbAccess = _fx.NewDbAccess(databaseId);

            // Minimal hand-written DDL, to focus on how Oracle executes with the session-level NLS settings,
            // independently of the pure syntax tests of `OracleCreateTableCommandBuilder`. Oracle has no
            // DROP TABLE IF EXISTS, so a PL/SQL block swallows ORA-00942 instead.
            string dropDdl =
                "BEGIN " +
                "  EXECUTE IMMEDIATE 'DROP TABLE \"CI_TEST\" CASCADE CONSTRAINTS'; " +
                "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; " +
                "END;";

            dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.NonQuery, dropDdl));
            dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.NonQuery,
                "CREATE TABLE \"CI_TEST\" (\"NAME\" VARCHAR2(50 CHAR) NOT NULL)"));

            try
            {
                dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.NonQuery,
                    "INSERT INTO \"CI_TEST\" (\"NAME\") VALUES ({0})", "Jeff"));

                var result = dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.Scalar,
                    "SELECT COUNT(*) FROM \"CI_TEST\" WHERE \"NAME\" = {0}", "jeff"));

                Assert.NotNull(result);
                Assert.Equal(1, Convert.ToInt32(result.Scalar!, CultureInfo.InvariantCulture));
            }
            finally
            {
                dbAccess.Execute(new Polhem.Db.DbCommandSpec(Polhem.Db.DbCommandKind.NonQuery, dropDdl));
            }
        }

        // ---------- quoted-lowercase end-to-end coverage ----------

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("FormSchema-driven INSERT/SELECT/UPDATE/DELETE work on a quoted-lowercase table")]
        public void FormCrud_QuotedLowercaseTable_InsertSelectUpdateDelete_Succeeds()
        {
            const string tableName = "tb_it_crud";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                CreateTable(dbAccess, BuildCrudTableSchema(tableName));

                var formSchema = BuildCrudFormSchema(tableName);
                var formBuilder = new OracleFormCommandBuilder(formSchema, _fx.GetRequiredService<IDefineAccess>());
                var rowId = Guid.NewGuid();

                // INSERT
                var insertRow = NewRow(formSchema, tableName, rowId, "alice", 10);
                int inserted = dbAccess.Execute(new InsertCommandBuilder(formSchema, DatabaseType.Oracle).Build("Foo", insertRow)).RowsAffected;
                Assert.Equal(1, inserted);

                // SELECT confirms that the INSERT landed (including the equality WHERE on rowId).
                var selectByRowId = formBuilder.BuildSelect("Foo", "name,qty",
                    FilterCondition.Equal(SysFields.RowId, rowId), null);
                var selectResult = dbAccess.Execute(selectByRowId);
                Assert.NotNull(selectResult.Table);
                Assert.Single(selectResult.Table!.Rows);
                Assert.Equal("alice", selectResult.Table.Rows[0]["name"]);
                Assert.Equal(10, Convert.ToInt32(selectResult.Table.Rows[0]["qty"], CultureInfo.InvariantCulture));

                // UPDATE
                var updateRow = ExistingRow(formSchema, tableName, rowId, "alice", 10);
                updateRow["name"] = "alice2";
                updateRow["qty"] = 99;
                int updated = dbAccess.Execute(new UpdateCommandBuilder(formSchema, DatabaseType.Oracle).Build("Foo", updateRow)).RowsAffected;
                Assert.Equal(1, updated);

                var afterUpdate = dbAccess.Execute(selectByRowId);
                Assert.Equal("alice2", afterUpdate.Table!.Rows[0]["name"]);
                Assert.Equal(99, Convert.ToInt32(afterUpdate.Table.Rows[0]["qty"], CultureInfo.InvariantCulture));

                // DELETE
                int deleted = dbAccess.Execute(
                    formBuilder.BuildDelete("Foo", FilterCondition.Equal(SysFields.RowId, rowId))).RowsAffected;
                Assert.Equal(1, deleted);

                var afterDelete = dbAccess.Execute(selectByRowId);
                Assert.Empty(afterDelete.Table!.Rows);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("The JOIN clause produced by FromBuilder runs on two quoted-lowercase tables with fields on both sides of ON")]
        public void Join_QuotedLowercaseTables_FromBuilderEmitsExecutableSql()
        {
            const string masterTable = "tb_it_master";
            const string detailTable = "tb_it_detail";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, detailTable);
            DropQuotedTable(dbAccess, masterTable);

            try
            {
                CreateTable(dbAccess, BuildMasterSchema(masterTable));
                CreateTable(dbAccess, BuildDetailSchema(detailTable));

                var masterId = Guid.NewGuid();
                dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery,
                    "INSERT INTO \"TB_IT_MASTER\" (\"SYS_ROWID\", \"NAME\") VALUES ({0}, {1})",
                    masterId, "M1"));
                dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery,
                    "INSERT INTO \"TB_IT_DETAIL\" (\"SYS_ROWID\", \"MASTER_ID\", \"AMOUNT\") VALUES ({0}, {1}, {2})",
                    Guid.NewGuid(), masterId, 250));

                // Drives `FromBuilder` directly: the FormSchema RelationField path needs a cross-form DefinePath setup,
                // which is beyond the quoting check. This focuses on whether `FromBuilder` quotes the tables on both
                // sides of the join and the fields on both sides of ON.
                var joins = new TableJoinCollection
                {
                    new TableJoin
                    {
                        Key = "j1",
                        JoinType = JoinType.Inner,
                        LeftAlias = "A",
                        LeftField = SysFields.RowId,
                        RightTable = detailTable,
                        RightAlias = "B",
                        RightField = "master_id",
                    },
                };

                string fromClause = new FromBuilder(DatabaseType.Oracle).Build(masterTable, joins);

                // The fragment produced by `FromBuilder` must contain fully double-quoted identifiers (the common
                // weak spot that hits ORA-00942 / ORA-00904).
                Assert.Contains("FROM \"TB_IT_MASTER\" A", fromClause);
                Assert.Contains("INNER JOIN \"TB_IT_DETAIL\" B", fromClause);
                Assert.Contains("A.\"SYS_ROWID\" = B.\"MASTER_ID\"", fromClause);

                var spec = new DbCommandSpec(DbCommandKind.DataTable,
                    $"SELECT A.\"NAME\", B.\"AMOUNT\" {fromClause} WHERE A.\"SYS_ROWID\" = {{0}}",
                    masterId);
                var result = dbAccess.Execute(spec);

                Assert.NotNull(result.Table);
                Assert.Single(result.Table!.Rows);
                Assert.Equal("M1", result.Table.Rows[0]["name"]);
                Assert.Equal(250, Convert.ToInt32(result.Table.Rows[0]["amount"], CultureInfo.InvariantCulture));
            }
            finally
            {
                DropQuotedTable(dbAccess, detailTable);
                DropQuotedTable(dbAccess, masterTable);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Fields named with Oracle reserved words (comment / order) support CRUD once quoted")]
        public void ReservedWordFieldName_QuotedLowercase_CrudSucceeds()
        {
            const string tableName = "tb_it_reserved";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                // "comment" and "order" are both Oracle reserved words. Missing the double quotes on either side is a
                // syntax error, so this checks a hard requirement of the quoting mechanism.
                var schema = new TableSchema { TableName = tableName };
                schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                schema.Fields!.Add("comment", "Comment", FieldDbType.String, 100);
                schema.Fields!.Add("order", "Order", FieldDbType.Integer);
                schema.Indexes!.AddPrimaryKey(SysFields.RowId);
                CreateTable(dbAccess, schema);

                var formSchema = new FormSchema("X", "X");
                var table = formSchema.Tables!.Add("Foo", "Foo");
                table.DbTableName = tableName;
                table.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                table.Fields!.Add(new FormField("comment", "Comment", FieldDbType.String) { MaxLength = 100 });
                table.Fields!.Add("order", "Order", FieldDbType.Integer);

                var formBuilder = new OracleFormCommandBuilder(formSchema, _fx.GetRequiredService<IDefineAccess>());
                var rowId = Guid.NewGuid();

                var insertRow = NewRow(formSchema, tableName, rowId);
                insertRow["comment"] = "hello";
                insertRow["order"] = 7;
                dbAccess.Execute(new InsertCommandBuilder(formSchema, DatabaseType.Oracle).Build("Foo", insertRow));

                var selected = dbAccess.Execute(formBuilder.BuildSelect("Foo", "comment,order",
                    FilterCondition.Equal("order", 7), null));
                Assert.NotNull(selected.Table);
                Assert.Single(selected.Table!.Rows);
                Assert.Equal("hello", selected.Table.Rows[0]["comment"]);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("OracleTableAlterCommandBuilder ADD column runs on a quoted-lowercase table and keeps the data")]
        public void AlterAddColumn_QuotedLowercaseTable_Succeeds()
        {
            // The Rebuild path (`OracleTableRebuildCommandBuilder.GetCommandText`) currently returns a
            // multi-statement script mixing PL/SQL blocks and plain SQL, and Oracle.ManagedDataAccess runs one
            // statement at a time. The caller would have to split the script and send it statement by statement, or
            // the builder API would have to become `GetStatements()`. So this test only covers Alter (which already
            // uses `GetStatements`); end-to-end verification of Rebuild is left for separate follow-up work.
            const string tableName = "tb_it_alter";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                var initial = new TableSchema { TableName = tableName };
                initial.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                initial.Fields!.Add("name", "Name", FieldDbType.String, 50);
                initial.Indexes!.AddPrimaryKey(SysFields.RowId);
                CreateTable(dbAccess, initial);

                var rowId = Guid.NewGuid();
                dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery,
                    "INSERT INTO \"TB_IT_ALTER\" (\"SYS_ROWID\", \"NAME\") VALUES ({0}, {1})",
                    rowId, "before"));

                var alterBuilder = new OracleTableAlterCommandBuilder();
                var addStatements = alterBuilder.GetStatements(tableName,
                    new Polhem.Db.Schema.Changes.AddFieldChange(
                        new DbField("age", "Age", FieldDbType.Integer) { AllowNull = true }));
                foreach (var stmt in addStatements)
                {
                    dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery, stmt));
                }

                var provider = new OracleTableSchemaProvider(TestDbConventions.GetDatabaseId(DatabaseType.Oracle), _fx.GetRequiredService<IDbConnectionManager>());
                var afterAlter = provider.GetTableSchema(tableName);
                Assert.NotNull(afterAlter);
                Assert.True(afterAlter!.Fields!.Contains("age"));

                var preserved = dbAccess.Execute(new DbCommandSpec(DbCommandKind.Scalar,
                    "SELECT \"NAME\" FROM \"TB_IT_ALTER\" WHERE \"SYS_ROWID\" = {0}", rowId));
                Assert.Equal("before", preserved.Scalar);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("OracleTableAlterCommandBuilder MODIFY of an existing NOT NULL field (nullability unchanged) does not raise ORA-01442")]
        public void AlterModify_RedundantNotNull_QuotedLowercaseTable_DoesNotRaiseOra01442()
        {
            const string tableName = "tb_it_modnull";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                // A table with a non-string NOT NULL field (qty defaults
                // to AllowNull=false, so NUMBER(10) DEFAULT 0 NOT NULL).
                var initial = new TableSchema { TableName = tableName };
                initial.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                initial.Fields!.Add("qty", "Qty", FieldDbType.Integer);
                initial.Indexes!.AddPrimaryKey(SysFields.RowId);
                CreateTable(dbAccess, initial);

                // ALTER the existing NOT NULL qty: nullability stays, only the default changes from 0 to 1.
                // Before the fix the builder re-emitted MODIFY (... NOT NULL), which raises ORA-01442 on a column that
                // is already NOT NULL. After the fix the redundant nullability hint is omitted and MODIFY succeeds.
                var oldField = new DbField("qty", "Qty", FieldDbType.Integer) { AllowNull = false, DefaultValue = "0" };
                var newField = new DbField("qty", "Qty", FieldDbType.Integer) { AllowNull = false, DefaultValue = "1" };
                var statements = new OracleTableAlterCommandBuilder()
                    .GetStatements(tableName, new Polhem.Db.Schema.Changes.AlterFieldChange(oldField, newField));

                var ex = Record.Exception(() =>
                {
                    foreach (var stmt in statements)
                        dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery, stmt));
                });

                Assert.Null(ex);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("An AllowNull=false String field is created nullable on Oracle: an INSERT omitting it succeeds, reads back an empty string, and a second diff is empty")]
        public void NonNullString_OracleNullable_OmittedInsertSucceedsAndDiffIsEmpty()
        {
            const string tableName = "tb_it_strnull";
            var dbAccess = _fx.NewDbAccess(TestDbConventions.GetDatabaseId(DatabaseType.Oracle));
            DropQuotedTable(dbAccess, tableName);

            try
            {
                // The definition still marks AllowNull=false (semantically "must
                // not be null"), a miniature of the customize_id case.
                var define = new TableSchema { TableName = tableName };
                define.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
                define.Fields!.Add("customize_id", "Customize", FieldDbType.String, 50);
                define.Indexes!.AddPrimaryKey(SysFields.RowId);
                CreateTable(dbAccess, define);

                // An INSERT omitting customize_id must not raise ORA-01400 (the column was created nullable).
                var rowId = Guid.NewGuid();
                var insert = Record.Exception(() => dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery,
                    "INSERT INTO \"TB_IT_STRNULL\" (\"SYS_ROWID\") VALUES ({0})", rowId)));
                Assert.Null(insert);

                // The customize_id read back is an Oracle NULL, normalized to an empty string by `ValueUtilities.CStr`.
                var read = dbAccess.Execute(new DbCommandSpec(DbCommandKind.Scalar,
                    "SELECT \"CUSTOMIZE_ID\" FROM \"TB_IT_STRNULL\" WHERE \"SYS_ROWID\" = {0}", rowId));
                Assert.Equal(string.Empty, ValueUtilities.CStr(read.Scalar!));

                // Upgrade idempotency: comparing the schema read back with the definition must produce no difference
                // for customize_id (the provider always reports AllowNull=false for String/Text to match the
                // definition).
                var provider = new OracleTableSchemaProvider(
                    TestDbConventions.GetDatabaseId(DatabaseType.Oracle), _fx.GetRequiredService<IDbConnectionManager>());
                var real = provider.GetTableSchema(tableName);
                Assert.NotNull(real);
                var defineField = define.Fields!["customize_id"];
                var realField = real!.Fields![defineField.FieldName];
                Assert.False(realField.AllowNull);
                Assert.True(defineField.Compare(realField));
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle upgrade adds a field to a table with a nullable Text field and is idempotent (regression for ORA-22859)")]
        public void Upgrade_TableWithNullableTextColumn_AddsColumnAndIsIdempotent()
        {
            const string tableName = "tb_it_lobupg";
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var connectionManager = _fx.GetRequiredService<IDbConnectionManager>();
            var dbAccess = _fx.NewDbAccess(databaseId);
            DropQuotedTable(dbAccess, tableName);

            try
            {
                // Create the table: the definition marks Text as AllowNull=true,
                // and Oracle always creates a nullable CLOB.
                var initial = BuildLobUpgradeSchema(tableName, includeAddedColumn: false);
                CreateTable(dbAccess, initial);

                // Upgrade: one more String field. The CLOB field itself did not change and must not get a MODIFY.
                var define = BuildLobUpgradeSchema(tableName, includeAddedColumn: true);
                var provider = new OracleTableSchemaProvider(databaseId, connectionManager);
                var orchestrator = new TableUpgradeOrchestrator(new OracleDialectFactory(), connectionManager);

                var diff = new TableSchemaComparer(define, provider.GetTableSchema(tableName), DatabaseType.Oracle).CompareToDiff();
                var plan = orchestrator.Plan(diff);
                // If the CLOB field were misjudged as changed, an extra AlterColumns stage would appear here and
                // Execute would throw ORA-22859.
                Assert.Equal(UpgradeExecutionMode.Alter, plan.Mode);
                var addChange = Assert.Single(diff.Changes);
                Assert.Equal("api_key_id", Assert.IsType<AddFieldChange>(addChange).Field.FieldName);

                orchestrator.Execute(plan, databaseId);

                var upgraded = provider.GetTableSchema(tableName);
                Assert.NotNull(upgraded);
                Assert.True(upgraded!.Fields!.Contains("api_key_id"));

                // Idempotency: a second comparison must produce no difference
                // (otherwise every startup reruns a failing upgrade).
                var secondDiff = new TableSchemaComparer(define, upgraded, DatabaseType.Oracle).CompareToDiff();
                Assert.Empty(secondDiff.Changes);
                // The plan that ALTERs in a field must also write its caption into USER_COL_COMMENTS. Otherwise the
                // caption of api_key_id always counts as a DescriptionChange, the diff is never empty, and
                // "is this table up to date" is always answered no.
                Assert.Empty(secondDiff.DescriptionChanges);
                Assert.True(secondDiff.IsEmpty);
                Assert.Equal(UpgradeExecutionMode.NoChange, orchestrator.Plan(secondDiff).Mode);
            }
            finally
            {
                DropQuotedTable(dbAccess, tableName);
            }
        }

        // ---------- helpers ----------

        private static TableSchema BuildLobUpgradeSchema(string tableName, bool includeAddedColumn)
        {
            var schema = new TableSchema { TableName = tableName };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields!.Add("user_id", "User", FieldDbType.String, 50).AllowNull = true;
            schema.Fields!.Add("error_message", "Message", FieldDbType.Text).AllowNull = true;
            if (includeAddedColumn)
                schema.Fields!.Add("api_key_id", "API Key", FieldDbType.String, 50).AllowNull = true;
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }


        private static TableSchema BuildCrudTableSchema(string tableName)
        {
            var schema = new TableSchema { TableName = tableName };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields!.Add("name", "Name", FieldDbType.String, 50);
            schema.Fields!.Add("qty", "Qty", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        private static FormSchema BuildCrudFormSchema(string tableName)
        {
            var schema = new FormSchema("X", "X");
            var table = schema.Tables!.Add("Foo", "Foo");
            table.DbTableName = tableName;
            table.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            table.Fields!.Add(new FormField("name", "Name", FieldDbType.String) { MaxLength = 50 });
            table.Fields!.Add("qty", "Qty", FieldDbType.Integer);
            return schema;
        }

        private static TableSchema BuildMasterSchema(string tableName)
        {
            var schema = new TableSchema { TableName = tableName };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields!.Add("name", "Name", FieldDbType.String, 50);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        private static TableSchema BuildDetailSchema(string tableName)
        {
            var schema = new TableSchema { TableName = tableName };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields!.Add("master_id", "Master ID", FieldDbType.Guid);
            schema.Fields!.Add("amount", "Amount", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        private static DataRow NewRow(FormSchema formSchema, string tableName, Guid rowId, string? name = null, int? qty = null)
        {
            var dt = BuildDataTable(formSchema, tableName);
            var row = dt.NewRow();
            row[SysFields.RowId] = rowId;
            if (name != null) row["name"] = name;
            if (qty != null) row["qty"] = qty.Value;
            return row;
        }

        private static DataRow ExistingRow(FormSchema formSchema, string tableName, Guid rowId, string name, int qty)
        {
            // The update path needs `row.RowState != Added`: Add and then AcceptChanges, so that later field changes
            // are detected as modified by `BuildUpdate`.
            var dt = BuildDataTable(formSchema, tableName);
            var row = dt.NewRow();
            row[SysFields.RowId] = rowId;
            row["name"] = name;
            row["qty"] = qty;
            dt.Rows.Add(row);
            dt.AcceptChanges();
            return row;
        }

        private static DataTable BuildDataTable(FormSchema formSchema, string tableName)
        {
            var formTable = formSchema.Tables!["Foo"]!;
            var dt = new DataTable(tableName);
            foreach (var field in formTable.Fields!)
            {
                dt.Columns.Add(field.FieldName, MapClrType(field.DbType));
            }
            return dt;
        }

        private static Type MapClrType(FieldDbType dbType) => dbType switch
        {
            FieldDbType.Guid => typeof(Guid),
            FieldDbType.String => typeof(string),
            FieldDbType.Integer => typeof(int),
            FieldDbType.Long => typeof(long),
            FieldDbType.Decimal => typeof(decimal),
            FieldDbType.DateTime => typeof(DateTime),
            FieldDbType.Date => typeof(DateTime),
            FieldDbType.Boolean => typeof(bool),
            _ => typeof(object),
        };

        private static void CreateTable(DbAccess dbAccess, TableSchema schema)
        {
            string sql = new OracleCreateTableCommandBuilder().GetCommandText(schema);
            dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery, sql));
        }

        private static void DropQuotedTable(DbAccess dbAccess, string tableName)
        {
            // Oracle has no DROP TABLE IF EXISTS, so it is wrapped in a PL/SQL block that swallows ORA-00942.
            // The framework stores names in UPPERCASE on Oracle (per `OracleSchemaSyntax.QuoteName`); this helper
            // builds the DDL directly, bypassing the framework, so it must uppercase the names itself to match.
            string storageName = tableName.ToUpperInvariant();
            string ddl =
                "BEGIN " +
                "  EXECUTE IMMEDIATE 'DROP TABLE \"" + storageName + "\" CASCADE CONSTRAINTS'; " +
                "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; " +
                "END;";
            dbAccess.Execute(new DbCommandSpec(DbCommandKind.NonQuery, ddl));
        }
    }
}
