using System.ComponentModel;
using Polhem.Core.Data;
using Polhem.Db.Providers.Oracle;
using Polhem.Definition;
using Polhem.Definition.Database;

namespace Polhem.Db.UnitTests
{
    /// <summary>
    /// Pure-syntax tests for <see cref="OracleCreateTableCommandBuilder"/>. No live database
    /// connection — the builder produces string output that is asserted via
    /// <see cref="Assert.Contains(string, string)"/> against the well-known fragments
    /// for Oracle 19c+ dialect (double-quote quoting, the NUMBER family, VARCHAR2(n CHAR),
    /// GENERATED BY DEFAULT AS IDENTITY, independent COMMENT ON statements).
    /// </summary>
    /// <remarks>
    /// All output is wrapped in a PL/SQL anonymous block so multiple DDL statements can
    /// be dispatched through Oracle.ManagedDataAccess in a single command. Inside the
    /// <c>EXECUTE IMMEDIATE</c> string literal, every single quote in the wrapped DDL is
    /// escaped to <c>''</c>; assertions on string-default and COMMENT fragments must
    /// account for this doubled-quote form.
    /// </remarks>
    public class OracleCreateTableCommandBuilderTests
    {
        private static TableSchema BuildSchema(FieldDbType dbType, int length = 0,
            int precision = 18, int scale = 0, bool allowNull = false, string defaultValue = "")
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            var field = schema.Fields.Add("col", "Col", dbType, length);
            field.Precision = precision;
            field.Scale = scale;
            field.AllowNull = allowNull;
            field.DefaultValue = defaultValue;
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        #region GetOracleType branches per FieldDbType

        [Theory]
        [InlineData(FieldDbType.Boolean, "NUMBER(1)")]
        [InlineData(FieldDbType.Short, "NUMBER(5)")]
        [InlineData(FieldDbType.Integer, "NUMBER(10)")]
        [InlineData(FieldDbType.Long, "NUMBER(19)")]
        [InlineData(FieldDbType.Currency, "NUMBER(19,4)")]
        [InlineData(FieldDbType.Date, "DATE")]
        [InlineData(FieldDbType.DateTime, "TIMESTAMP(6)")]
        [InlineData(FieldDbType.Time, "VARCHAR2(5)")]
        [InlineData(FieldDbType.Guid, "RAW(16)")]
        [InlineData(FieldDbType.Binary, "BLOB")]
        [InlineData(FieldDbType.Text, "CLOB")]
        [DisplayName("GetCommandText produces the matching Oracle type string for each FieldDbType")]
        public void GetCommandText_FieldDbType_GeneratesCorrectColumnType(FieldDbType dbType, string expectedFragment)
        {
            var schema = BuildSchema(dbType);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains(expectedFragment, sql);
        }

        [Fact]
        [DisplayName("GetCommandText uses VARCHAR2(n CHAR) with the character length for the String type")]
        public void GetCommandText_String_UsesVarchar2CharSemantics()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // CHAR semantics keep Chinese and other multi-byte characters from being truncated.
            Assert.Contains("VARCHAR2(50 CHAR)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText uses CLOB for a String longer than the 4000-byte limit")]
        public void GetCommandText_StringOverVarcharLimit_FallsBackToClob()
        {
            var schema = BuildSchema(FieldDbType.String, length: 8000);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // The standard VARCHAR2 limit is 4000 bytes. Beyond it the type
            // falls back to CLOB instead of relying on EXTENDED mode.
            Assert.Contains("\"COL\" CLOB", sql);
            Assert.DoesNotContain("VARCHAR2", sql);
        }

        [Fact]
        [DisplayName("GetCommandText uses CLOB for a String of length 0")]
        public void GetCommandText_StringZeroLength_FallsBackToClob()
        {
            var schema = BuildSchema(FieldDbType.String, length: 0);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"COL\" CLOB", sql);
        }

        [Fact]
        [DisplayName("GetCommandText uses NUMBER(precision,scale) for Decimal")]
        public void GetCommandText_Decimal_UsesNumberPrecisionScale()
        {
            var schema = BuildSchema(FieldDbType.Decimal, precision: 12, scale: 3);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("NUMBER(12,3)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText throws InvalidOperationException for an unsupported FieldDbType")]
        public void GetCommandText_UnknownDbType_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("col", "Col", (FieldDbType)999);
            var builder = new OracleCreateTableCommandBuilder();

            Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
        }

        #endregion

        #region Identifier quoting and table suffix

        [Fact]
        [DisplayName("Identifiers are quoted with double quotes (Oracle has many reserved words, so quoting statically is the safe policy)")]
        public void GetCommandText_Identifiers_UseDoubleQuotes()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CREATE TABLE \"ST_DEMO\"", sql);
            Assert.Contains("\"COL\"", sql);
        }

        [Fact]
        [DisplayName("CREATE TABLE carries no ENGINE / CHARSET / COLLATE suffix (Oracle uses the database defaults)")]
        public void GetCommandText_NoTableSuffix()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Oracle uses session-level NLS settings (the ALTER SESSION that
            // `SharedDatabaseState` attaches) instead of a column-level COLLATE.
            Assert.DoesNotContain("ENGINE=", sql);
            Assert.DoesNotContain("CHARSET=", sql);
            Assert.DoesNotContain("COLLATE", sql);
        }

        [Fact]
        [DisplayName("An identifier containing special characters (double quotes) is escaped")]
        public void GetCommandText_IdentifierWithDoubleQuote_IsEscaped()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields.Add("col\"x", "Col", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"COL\"\"X\"", sql);
        }

        #endregion

        #region Default Expressions

        [Fact]
        [DisplayName("A non-AllowNull Integer field produces DEFAULT 0 NOT NULL (Oracle's order is type DEFAULT NOT NULL)")]
        public void GetCommandText_NonNullInteger_GeneratesDefault0NotNull()
        {
            var schema = BuildSchema(FieldDbType.Integer, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"COL\" NUMBER(10) DEFAULT 0 NOT NULL", sql);
        }

        [Fact]
        [DisplayName("A non-AllowNull String field (no explicit default) is created nullable without a DEFAULT")]
        public void GetCommandText_NonNullString_EmitsNullableWithoutDefault()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Oracle treats '' as NULL, so DEFAULT '' means DEFAULT NULL, which contradicts NOT NULL. A String field
            // with AllowNull=false in the definition is therefore always created nullable without a DEFAULT, and the
            // C# layer keeps the "never null" semantics with `ValueUtilities.CStr(null)` returning "".
            Assert.Contains("\"COL\" VARCHAR2(50 CHAR) NULL", sql);
            Assert.DoesNotContain("\"COL\" VARCHAR2(50 CHAR) DEFAULT", sql);
            Assert.DoesNotContain("\"COL\" VARCHAR2(50 CHAR) NOT NULL", sql);
        }

        [Fact]
        [DisplayName("An AllowNull field has no DEFAULT clause")]
        public void GetCommandText_AllowNullField_OmitsDefault()
        {
            var schema = BuildSchema(FieldDbType.Integer, allowNull: true);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"COL\" NUMBER(10) NULL", sql);
            Assert.DoesNotContain("\"COL\" NUMBER(10) DEFAULT", sql);
        }

        [Fact]
        [DisplayName("A Guid field DEFAULT is SYS_GUID()")]
        public void GetCommandText_NonNullGuid_GeneratesSysGuidDefault()
        {
            var schema = BuildSchema(FieldDbType.Guid, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT SYS_GUID()", sql);
        }

        [Fact]
        [DisplayName("A DateTime field DEFAULT is SYS_EXTRACT_UTC(SYSTIMESTAMP)")]
        public void GetCommandText_NonNullDateTime_GeneratesSystimestampDefault()
        {
            var schema = BuildSchema(FieldDbType.DateTime, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)", sql);
        }

        [Fact]
        [DisplayName("A Text field (CLOB) is created nullable without a DEFAULT (the same '' == NULL rule as String)")]
        public void GetCommandText_Text_EmitsNullableWithoutDefault()
        {
            var textSchema = new TableSchema { TableName = "st_demo" };
            textSchema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            textSchema.Fields.Add("note", "Note", FieldDbType.Text);
            textSchema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(textSchema);

            Assert.Contains("\"NOTE\" CLOB NULL", sql);
            Assert.DoesNotContain("\"NOTE\" CLOB DEFAULT", sql);
            Assert.DoesNotContain("\"NOTE\" CLOB NOT NULL", sql);
        }

        [Fact]
        [DisplayName("A Binary field (BLOB) produces no DEFAULT even when NOT NULL (a BLOB restriction)")]
        public void GetCommandText_Binary_OmitsDefault()
        {
            var binarySchema = new TableSchema { TableName = "st_demo" };
            binarySchema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            binarySchema.Fields.Add("blob", "Blob", FieldDbType.Binary);
            binarySchema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(binarySchema);

            Assert.Contains("\"BLOB\" BLOB NOT NULL", sql);
            Assert.DoesNotContain("\"BLOB\" BLOB DEFAULT", sql);
        }

        [Fact]
        [DisplayName("A String DEFAULT containing a single quote becomes ''O''''Brien'' after the double PL/SQL escape")]
        public void GetCommandText_StringDefaultWithQuote_IsEscaped()
        {
            var schema = BuildSchema(FieldDbType.String, length: 20, defaultValue: "O'Brien");
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Two levels of escaping: inside the PL/SQL `EXECUTE IMMEDIATE` literal, every single quote of the original
            // DEFAULT 'O''Brien' is escaped once more, so all single quotes end up doubled.
            Assert.Contains("DEFAULT ''O''''Brien''", sql);
        }

        #endregion

        #region AutoIncrement

        [Fact]
        [DisplayName("An AutoIncrement field produces NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL")]
        public void GetCommandText_AutoIncrement_UsesIdentitySyntax()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            schema.Indexes!.AddPrimaryKey("sys_no");
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"SYS_NO\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
            // Oracle does not allow an inline column-level PRIMARY KEY; it must be a table-level CONSTRAINT.
            Assert.Contains("CONSTRAINT", sql);
            Assert.Contains("PRIMARY KEY (\"SYS_NO\")", sql);
        }

        [Fact]
        [DisplayName("An AutoIncrement field that is not a single-column PK throws InvalidOperationException")]
        public void GetCommandText_AutoIncrementNotSinglePk_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            schema.Fields!.Add("other", "Other", FieldDbType.String, 10);
            schema.Indexes!.AddPrimaryKey("other");

            var builder = new OracleCreateTableCommandBuilder();
            var ex = Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
            Assert.Contains("must be the single-column primary key", ex.Message);
        }

        [Fact]
        [DisplayName("An AutoIncrement field without a declared PK gets pk_{table name} as the PK constraint name")]
        public void GetCommandText_AutoIncrementWithoutDeclaredPk_UsesDefaultPkName()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            // No PK in Indexes; the builder generates the PK constraint.
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"SYS_NO\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
            Assert.Contains("CONSTRAINT \"PK_ST_DEMO\" PRIMARY KEY (\"SYS_NO\")", sql);
        }

        [Fact]
        [DisplayName("Several AutoIncrement fields throw InvalidOperationException")]
        public void GetCommandText_MultipleAutoIncrement_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("a", "A", FieldDbType.AutoIncrement);
            schema.Fields!.Add("b", "B", FieldDbType.AutoIncrement);
            schema.Indexes!.AddPrimaryKey("a");

            var builder = new OracleCreateTableCommandBuilder();
            var ex = Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
            Assert.Contains("at most one IDENTITY", ex.Message);
        }

        #endregion

        #region PRIMARY KEY and indexes

        [Fact]
        [DisplayName("A schema without AutoIncrement produces a separate PRIMARY KEY constraint")]
        public void GetCommandText_NonAutoIncrementSchema_EmitsPrimaryKeyConstraint()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CONSTRAINT \"PK_ST_DEMO\" PRIMARY KEY (\"SYS_ROWID\")", sql);
        }

        [Fact]
        [DisplayName("The PK constraint carries no ASC/DESC direction (an Oracle syntax restriction)")]
        public void GetCommandText_PrimaryKey_OmitsSortDirection()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Columns inside an Oracle PRIMARY KEY constraint do not accept ASC/DESC.
            Assert.DoesNotContain("PRIMARY KEY (\"SYS_ROWID\" ASC)", sql);
            Assert.DoesNotContain("PRIMARY KEY (\"SYS_ROWID\" DESC)", sql);
        }

        [Fact]
        [DisplayName("A non-PK index produces a CREATE INDEX statement with ASC/DESC (no trailing semicolon inside EXECUTE IMMEDIATE)")]
        public void GetCommandText_NonPkIndexes_EmitCreateIndexStatements()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.Indexes!.Add("ix_{0}_col", "col", false);
            schema.Indexes!.Add("uk_{0}_col", "col", true);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("CREATE INDEX \"IX_ST_DEMO_COL\" ON \"ST_DEMO\" (\"COL\" ASC)", sql);
            Assert.Contains("CREATE UNIQUE INDEX \"UK_ST_DEMO_COL\" ON \"ST_DEMO\" (\"COL\" ASC)", sql);
        }

        #endregion

        #region COMMENT ON

        [Fact]
        [DisplayName("A non-empty DisplayName produces a separate COMMENT ON TABLE statement (the string after IS is PL/SQL-escaped)")]
        public void GetCommandText_DisplayName_EmitsCommentOnTable()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "示範資料表";

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON TABLE \"ST_DEMO\" IS ''示範資料表''", sql);
        }

        [Fact]
        [DisplayName("An empty DisplayName produces no COMMENT ON TABLE statement")]
        public void GetCommandText_NoDisplayName_OmitsCommentOnTable()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.DoesNotContain("COMMENT ON TABLE", sql);
        }

        [Fact]
        [DisplayName("A field with a non-empty Caption produces its COMMENT ON COLUMN statement (after the PL/SQL escape)")]
        public void GetCommandText_FieldCaption_EmitsCommentOnColumn()
        {
            var schema = BuildSchema(FieldDbType.Integer);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON COLUMN \"ST_DEMO\".\"SYS_ROWID\" IS ''Row ID''", sql);
            Assert.Contains("COMMENT ON COLUMN \"ST_DEMO\".\"COL\" IS ''Col''", sql);
        }

        [Fact]
        [DisplayName("A Caption containing a single quote becomes ''User''''s note'' after the double PL/SQL escape")]
        public void GetCommandText_CaptionWithQuote_IsEscaped()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields.Add("col", "User's note", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            // Two levels of escaping: the caption 'User''s note' (the original SQL) is escaped once more inside the
            // PL/SQL `EXECUTE IMMEDIATE` literal.
            Assert.Contains("COMMENT ON COLUMN \"ST_DEMO\".\"COL\" IS ''User''''s note''", sql);
        }

        [Fact]
        [DisplayName("The whole output is wrapped in a PL/SQL anonymous block (BEGIN/END + EXECUTE IMMEDIATE)")]
        public void GetCommandText_WrapsInPlSqlBlock()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("BEGIN", sql);
            Assert.Contains("EXECUTE IMMEDIATE 'CREATE TABLE \"ST_DEMO\"", sql);
            Assert.EndsWith("END;", sql);
        }

        #endregion
    }
}
