using System.ComponentModel;
using Polhem.Base.Data;
using Polhem.Db.Providers.PostgreSql;
using Polhem.Definition;
using Polhem.Definition.Database;

namespace Polhem.Db.UnitTests
{
    public class PgCreateTableCommandBuilderTests
    {
        private static TableSchema BuildSchema(FieldDbType dbType, int length = 0,
            int precision = 18, int scale = 0, bool allowNull = false, string defaultValue = "")
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            var field = schema.Fields.Add("col", "Col", dbType, length);
            field.Precision = precision;
            field.Scale = scale;
            field.AllowNull = allowNull;
            field.DefaultValue = defaultValue;
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        #region GetPgType 各 FieldDbType 分支

        [Theory]
        [InlineData(FieldDbType.Boolean, "boolean")]
        [InlineData(FieldDbType.AutoIncrement, "integer GENERATED BY DEFAULT AS IDENTITY")]
        [InlineData(FieldDbType.Short, "smallint")]
        [InlineData(FieldDbType.Integer, "integer")]
        [InlineData(FieldDbType.Long, "bigint")]
        [InlineData(FieldDbType.Currency, "numeric(19,4)")]
        [InlineData(FieldDbType.Date, "date")]
        [InlineData(FieldDbType.DateTime, "timestamp")]
        [InlineData(FieldDbType.Time, "char(5)")]
        [InlineData(FieldDbType.Guid, "uuid")]
        [InlineData(FieldDbType.Binary, "bytea")]
        [InlineData(FieldDbType.Text, "text")]
        [DisplayName("GetCommandText 應為各 FieldDbType 產生對應的 PostgreSQL 型別字串")]
        public void GetCommandText_FieldDbType_GeneratesCorrectColumnType(FieldDbType dbType, string expectedFragment)
        {
            var schema = BuildSchema(dbType);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains(expectedFragment, sql);
        }

        [Fact]
        [DisplayName("GetCommandText String 型別應使用 varchar 並指定長度")]
        public void GetCommandText_String_UsesVarcharLength()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("varchar(50)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText Decimal 應使用 numeric(precision,scale)")]
        public void GetCommandText_Decimal_UsesNumeric()
        {
            var schema = BuildSchema(FieldDbType.Decimal, precision: 12, scale: 3);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("numeric(12,3)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText 不支援的 FieldDbType 應擲出 InvalidOperationException")]
        public void GetCommandText_UnknownDbType_Throws()
        {
            var schema = BuildSchema(FieldDbType.Unknown);
            var builder = new PgCreateTableCommandBuilder();

            Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
        }

        #endregion

        #region 結構與分支

        [Fact]
        [DisplayName("GetCommandText 應產生雙引號 quoted 的 CREATE TABLE 語句")]
        public void GetCommandText_New_GeneratesCreateTable()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.UpgradeAction = DbUpgradeAction.New;
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("-- Create table st_demo", sql);
            Assert.Contains("CREATE TABLE \"st_demo\"", sql);
        }

        [Fact]
        [DisplayName("含 PrimaryKey 索引時應產生 CONSTRAINT ... PRIMARY KEY 語句")]
        public void GetCommandText_PrimaryKey_GeneratesConstraint()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CONSTRAINT \"pk_st_demo\" PRIMARY KEY", sql);
            Assert.Contains("\"sys_rowid\"", sql);
        }

        [Fact]
        [DisplayName("含獨立索引時應產生 CREATE INDEX 與 CREATE UNIQUE INDEX")]
        public void GetCommandText_Indexes_GeneratesCreateIndex()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.Indexes!.Add("ix_{0}_col", "col", false);
            schema.Indexes!.Add("uk_{0}_col", "col", true);

            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CREATE INDEX \"ix_st_demo_col\" ON \"st_demo\"", sql);
            Assert.Contains("CREATE UNIQUE INDEX \"uk_st_demo_col\" ON \"st_demo\"", sql);
        }

        [Fact]
        [DisplayName("AllowNull 欄位應產生 NULL 標記且無 DEFAULT 子句")]
        public void GetCommandText_AllowNull_GeneratesNullWithoutDefault()
        {
            var schema = BuildSchema(FieldDbType.Integer, allowNull: true);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" integer NULL", sql);
            Assert.DoesNotContain("\"col\" integer NULL DEFAULT", sql);
        }

        [Fact]
        [DisplayName("非 AllowNull Integer 欄位應產生 NOT NULL DEFAULT 0")]
        public void GetCommandText_NotNullInteger_GeneratesDefaultZero()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" integer NOT NULL DEFAULT 0", sql);
        }

        [Fact]
        [DisplayName("String 欄位應產生 '' 預設值（不加 N 前綴）")]
        public void GetCommandText_String_GeneratesEmptyStringDefault()
        {
            var schema = BuildSchema(FieldDbType.String, length: 20);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT ''", sql);
            Assert.DoesNotContain("DEFAULT N'", sql);
        }

        [Fact]
        [DisplayName("自訂 DefaultValue 應寫入 DEFAULT 子句")]
        public void GetCommandText_CustomDefault_AppliedToColumn()
        {
            var schema = BuildSchema(FieldDbType.Integer, defaultValue: "42");
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT 42", sql);
        }

        [Fact]
        [DisplayName("DateTime 欄位應使用 (NOW() AT TIME ZONE 'UTC') 作為預設值")]
        public void GetCommandText_DateTime_DefaultCurrentTimestamp()
        {
            var schema = BuildSchema(FieldDbType.DateTime);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT (NOW() AT TIME ZONE 'UTC')", sql);
        }

        [Fact]
        [DisplayName("Guid 欄位應使用 gen_random_uuid() 作為預設值")]
        public void GetCommandText_Guid_DefaultGenRandomUuid()
        {
            var schema = BuildSchema(FieldDbType.Guid);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT gen_random_uuid()", sql);
        }

        [Fact]
        [DisplayName("AutoIncrement 欄位不應產生 DEFAULT 子句")]
        public void GetCommandText_AutoIncrement_NoDefault()
        {
            var schema = BuildSchema(FieldDbType.AutoIncrement);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
            Assert.DoesNotContain("\"col\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL DEFAULT", sql);
        }

        #endregion

        #region COMMENT ON 產出

        [Fact]
        [DisplayName("GetCommandText 有 DisplayName 與 Caption 時應產生 COMMENT ON 語句")]
        public void GetCommandText_WithDisplayNameAndCaption_IncludesComments()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "示範資料表";
            schema.Fields!["col"].Caption = "數值欄位";

            var builder = new PgCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON TABLE \"st_demo\" IS '示範資料表';", sql);
            Assert.Contains("COMMENT ON COLUMN \"st_demo\".\"col\" IS '數值欄位';", sql);
        }

        [Fact]
        [DisplayName("GetCommandText DisplayName 為空時不產生 COMMENT ON TABLE")]
        public void GetCommandText_WithEmptyDisplayName_OmitsTableComment()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.Fields!["col"].Caption = "數值欄位";

            var builder = new PgCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.DoesNotContain("COMMENT ON TABLE", sql);
            Assert.Contains("COMMENT ON COLUMN \"st_demo\".\"col\"", sql);
        }

        [Fact]
        [DisplayName("GetCommandText Caption 為空的欄位不產生 COMMENT ON COLUMN")]
        public void GetCommandText_WithEmptyCaption_OmitsColumnComment()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "示範資料表";
            schema.Fields!["col"].Caption = string.Empty;
            schema.Fields![SysFields.RowId].Caption = string.Empty;

            var builder = new PgCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON TABLE \"st_demo\" IS '示範資料表'", sql);
            Assert.DoesNotContain("COMMENT ON COLUMN", sql);
        }

        [Fact]
        [DisplayName("GetCommandText 含單引號時應正確 escape 為雙單引號")]
        public void GetCommandText_WithSingleQuote_EscapesCorrectly()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "O'Brien 表";
            schema.Fields!["col"].Caption = "it's a field";

            var builder = new PgCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("IS 'O''Brien 表'", sql);
            Assert.Contains("IS 'it''s a field'", sql);
        }

        #endregion
    }
}
