using System.ComponentModel;
using Polhem.Core.Data;
using Polhem.Db.Providers.PostgreSql;
using Polhem.Definition;
using Polhem.Definition.Database;

namespace Polhem.Db.UnitTests
{
    public class PgCreateTableCommandBuilderTests
    {
        private static TableSchema BuildSchema(FieldDbType dbType, int length = 0,
            int precision = 18, int scale = 0, bool allowNull = false, string defaultValue = "")
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            var field = schema.Fields.Add("col", "Col", dbType, length);
            field.Precision = precision;
            field.Scale = scale;
            field.AllowNull = allowNull;
            field.DefaultValue = defaultValue;
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        #region GetPgType branches per FieldDbType

        [Theory]
        [InlineData(FieldDbType.Boolean, "boolean")]
        [InlineData(FieldDbType.AutoIncrement, "integer GENERATED BY DEFAULT AS IDENTITY")]
        [InlineData(FieldDbType.Short, "smallint")]
        [InlineData(FieldDbType.Integer, "integer")]
        [InlineData(FieldDbType.Long, "bigint")]
        [InlineData(FieldDbType.Currency, "numeric(19,4)")]
        [InlineData(FieldDbType.Date, "date")]
        [InlineData(FieldDbType.DateTime, "timestamp")]
        [InlineData(FieldDbType.Time, "char(5)")]
        [InlineData(FieldDbType.Guid, "uuid")]
        [InlineData(FieldDbType.Binary, "bytea")]
        [InlineData(FieldDbType.Text, "text")]
        [DisplayName("GetCommandText produces the matching PostgreSQL type string for each FieldDbType")]
        public void GetCommandText_FieldDbType_GeneratesCorrectColumnType(FieldDbType dbType, string expectedFragment)
        {
            var schema = BuildSchema(dbType);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains(expectedFragment, sql);
        }

        [Fact]
        [DisplayName("GetCommandText uses varchar with the length for the String type")]
        public void GetCommandText_String_UsesVarcharLength()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("varchar(50)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText uses numeric(precision,scale) for Decimal")]
        public void GetCommandText_Decimal_UsesNumeric()
        {
            var schema = BuildSchema(FieldDbType.Decimal, precision: 12, scale: 3);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("numeric(12,3)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText throws InvalidOperationException for an unsupported FieldDbType")]
        public void GetCommandText_UnknownDbType_Throws()
        {
            var schema = BuildSchema(FieldDbType.Unknown);
            var builder = new PgCreateTableCommandBuilder();

            Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
        }

        #endregion

        #region Structure and branches

        [Fact]
        [DisplayName("GetCommandText produces a CREATE TABLE statement with double-quoted identifiers")]
        public void GetCommandText_New_GeneratesCreateTable()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("-- Create table st_demo", sql);
            Assert.Contains("CREATE TABLE \"st_demo\"", sql);
        }

        [Fact]
        [DisplayName("A PrimaryKey index produces a CONSTRAINT ... PRIMARY KEY statement")]
        public void GetCommandText_PrimaryKey_GeneratesConstraint()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CONSTRAINT \"pk_st_demo\" PRIMARY KEY", sql);
            Assert.Contains("\"sys_rowid\"", sql);
        }

        [Fact]
        [DisplayName("Separate indexes produce CREATE INDEX and CREATE UNIQUE INDEX")]
        public void GetCommandText_Indexes_GeneratesCreateIndex()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.Indexes!.Add("ix_{0}_col", "col", false);
            schema.Indexes!.Add("uk_{0}_col", "col", true);

            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CREATE INDEX \"ix_st_demo_col\" ON \"st_demo\"", sql);
            Assert.Contains("CREATE UNIQUE INDEX \"uk_st_demo_col\" ON \"st_demo\"", sql);
        }

        [Fact]
        [DisplayName("An AllowNull field produces the NULL marker and no DEFAULT clause")]
        public void GetCommandText_AllowNull_GeneratesNullWithoutDefault()
        {
            var schema = BuildSchema(FieldDbType.Integer, allowNull: true);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" integer NULL", sql);
            Assert.DoesNotContain("\"col\" integer NULL DEFAULT", sql);
        }

        [Fact]
        [DisplayName("A non-AllowNull Integer field produces NOT NULL DEFAULT 0")]
        public void GetCommandText_NotNullInteger_GeneratesDefaultZero()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" integer NOT NULL DEFAULT 0", sql);
        }

        [Fact]
        [DisplayName("A String field produces a '' default (without the N prefix)")]
        public void GetCommandText_String_GeneratesEmptyStringDefault()
        {
            var schema = BuildSchema(FieldDbType.String, length: 20);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT ''", sql);
            Assert.DoesNotContain("DEFAULT N'", sql);
        }

        [Fact]
        [DisplayName("A custom DefaultValue is written into the DEFAULT clause")]
        public void GetCommandText_CustomDefault_AppliedToColumn()
        {
            var schema = BuildSchema(FieldDbType.Integer, defaultValue: "42");
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT 42", sql);
        }

        [Fact]
        [DisplayName("A DateTime field uses (NOW() AT TIME ZONE 'UTC') as the default")]
        public void GetCommandText_DateTime_DefaultCurrentTimestamp()
        {
            var schema = BuildSchema(FieldDbType.DateTime);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT (NOW() AT TIME ZONE 'UTC')", sql);
        }

        [Fact]
        [DisplayName("A Guid field uses gen_random_uuid() as the default")]
        public void GetCommandText_Guid_DefaultGenRandomUuid()
        {
            var schema = BuildSchema(FieldDbType.Guid);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT gen_random_uuid()", sql);
        }

        [Fact]
        [DisplayName("An AutoIncrement field produces no DEFAULT clause")]
        public void GetCommandText_AutoIncrement_NoDefault()
        {
            var schema = BuildSchema(FieldDbType.AutoIncrement);
            var builder = new PgCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
            Assert.DoesNotContain("\"col\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL DEFAULT", sql);
        }

        #endregion

        #region COMMENT ON output

        [Fact]
        [DisplayName("GetCommandText produces COMMENT ON statements when DisplayName and Caption are set")]
        public void GetCommandText_WithDisplayNameAndCaption_IncludesComments()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "示範資料表";
            schema.Fields!["col"].Caption = "數值欄位";

            var builder = new PgCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON TABLE \"st_demo\" IS '示範資料表';", sql);
            Assert.Contains("COMMENT ON COLUMN \"st_demo\".\"col\" IS '數值欄位';", sql);
        }

        [Fact]
        [DisplayName("GetCommandText produces no COMMENT ON TABLE when DisplayName is empty")]
        public void GetCommandText_WithEmptyDisplayName_OmitsTableComment()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.Fields!["col"].Caption = "數值欄位";

            var builder = new PgCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.DoesNotContain("COMMENT ON TABLE", sql);
            Assert.Contains("COMMENT ON COLUMN \"st_demo\".\"col\"", sql);
        }

        [Fact]
        [DisplayName("GetCommandText produces no COMMENT ON COLUMN for a field with an empty Caption")]
        public void GetCommandText_WithEmptyCaption_OmitsColumnComment()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "示範資料表";
            schema.Fields!["col"].Caption = string.Empty;
            schema.Fields![SysFields.RowId].Caption = string.Empty;

            var builder = new PgCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON TABLE \"st_demo\" IS '示範資料表'", sql);
            Assert.DoesNotContain("COMMENT ON COLUMN", sql);
        }

        [Fact]
        [DisplayName("GetCommandText escapes a single quote as two single quotes")]
        public void GetCommandText_WithSingleQuote_EscapesCorrectly()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "O'Brien 表";
            schema.Fields!["col"].Caption = "it's a field";

            var builder = new PgCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("IS 'O''Brien 表'", sql);
            Assert.Contains("IS 'it''s a field'", sql);
        }

        #endregion
    }
}
