<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Description>Defines the interface contracts for the business layer to access the data layer, serving as the boundary between the business logic layer and the data access layer.</Description>
    <PackageTags>polhem;repository;abstractions;dataaccess;contract;backend</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Polhem.Definition\Polhem.Definition.csproj" />
  </ItemGroup>

</Project>