@baseUrl = https://localhost:7056
@apiKey = test-api-key
@accessToken = Bearer 22AC9A7C-6E76-4C07-8560-89784D86AA76

// Ping method
POST {{baseUrl}}/api
Accept: application/json
content-type: application/json
X-Api-Key: {{apiKey}}

{
  "jsonrpc": "2.0",
  "method": "System.Ping",
  "params": {
    "value": {
      "$type": "Polhem.Define.PingArgs, Polhem.Define",
      "clientName": "TestClient",
      "traceId": "001"
    }
  },
  "id": "87267656-4a25-499a-bfbd-18b6b57cabf0"
}
###

POST {{baseUrl}}/api
Accept: application/json
content-type: application/json
X-Api-Key: {{apiKey}}
Authorization: {{accessToken}}

{
  "jsonrpc": "2.0",
  "method": "System.ExecFunc",
  "params": {
    "value": {
      "$type": "Polhem.Define.ExecFuncArgs, Polhem.Define",
      "funcId": "Hello"
    }
  },
  "id": "228bd7e0-603f-4433-93d9-9c03ebabc5e4"
}
###

